"""Offline integration tests against the same generated site in the portable review.
Requires Python playwright and Chromium. No network or production payment calls.
"""
from pathlib import Path
import json, os
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1]
results=[]
def record(name, ok=True, detail=''):
    results.append({'test':name,'passed':bool(ok),'detail':detail});print(name, 'PASS' if ok else 'FAIL',flush=True)
    if not ok: raise AssertionError(name+': '+detail)
with sync_playwright() as w:
    b=w.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    p=b.new_page(viewport={'width':1440,'height':1000})
    p.set_default_timeout(4000)
    errors=[]
    p.on('pageerror', lambda e:errors.append(str(e)))
    p.set_content((R/'nutrition-fitness-review.html').read_text(),wait_until='load')
    def nav(url):
        p.evaluate('(u)=>nfNavigate(u)',url)
        p.wait_for_timeout(150)
        f=p.frames[1]
        f.wait_for_selector('.bag-button')
        return f
    f=nav('/shop/')
    record('Catalogue displays 13 products', f.locator('.filter-status').inner_text()=='13 results')
    f.locator('[data-filter="shots"]').click()
    record('Flavour-shot filter shows 6 separate flavours', f.locator('.product-card:visible').count()==6)
    f.locator('[data-catalogue-search]').fill('banana')
    record('Catalogue text search narrows the active filter',f.locator('.product-card:visible').count()==1)
    f.locator('[data-catalogue-search]').fill('nonsense-does-not-exist')
    record('No-results state is clear',f.locator('.product-card:visible').count()==0 and 'Nothing' in f.locator('.filter-status').inner_text())
    f=nav('/shop/plain-whey/')
    record('One-off purchase is the default',f.locator('input[name="purchase"][value="once"]').is_checked())
    f.locator('input[name="purchase"][value="subscription"]').check()
    f.locator('.flavour-addons summary').click()
    f.locator('input[name="shot"][value="shot-vanilla"]').check()
    f.locator('#product-form button[type=submit]').click()
    f=nav('/basket/')
    record('One recurring powder plus one one-off shot preserved',f.locator('.basket-row').count()==2 and '£37.00' in f.locator('.grand').inner_text() and '£30.05 every 4 weeks' in f.locator('.renewal-note').inner_text())
    f.locator('[data-quantity="0"][data-change="1"]').click()
    record('Quantity recalculates totals and free shipping', '£59.15' in f.locator('.grand').inner_text())
    f.locator('[data-line-cadence="0"]').select_option('8w')
    record('Cadence edit changes renewal display', 'every 8 weeks' in f.locator('.renewal-note').inner_text())
    f.locator('[data-switch-once]').click()
    record('Switch to one-off updates price and removes renewal',f.locator('.renewal-note').count()==0 and '£64.95' in f.locator('.grand').inner_text())
    f.locator('[data-remove-line="0"]').click()
    record('Remove item updates basket',f.locator('.basket-row').count()==1)
    p.evaluate("nfStorage.removeItem('nutrition-fitness-site-v2')")
    f=nav('/subscriptions/')
    f.locator('input[name="box-shot"][value="shot-chocolate"]').check()
    f.locator('[data-shot-quantity="shot-chocolate"]').fill('2')
    f.locator('#add-nufi').check()
    record('Builder shows physical and calendar-month renewals separately',f.locator('#box-summary .renewal-note').count()==2)
    f.locator('#box-form button[type=submit]').click()
    f=nav('/basket/')
    record('Box selections persist across pages',f.locator('.basket-row').count()==3 and '£57.56' in f.locator('.grand').inner_text())
    f=nav('/checkout/')
    record('Checkout consent is not preselected',not f.locator('input[name=understood]').is_checked())
    f.locator('#review-form button[type=submit]').click()
    record('Checkout does not submit without consent',p.evaluate('nfRoute.pathname').startswith('/checkout/') and 'thanks' not in p.evaluate('nfRoute.pathname'))
    f.locator('input[name=understood]').check()
    f.locator('#review-form button[type=submit]').click()
    p.wait_for_timeout(200)
    f=p.frames[1]
    record('Demo checkout reaches explicitly labelled receipt','thanks' in p.evaluate('nfRoute.pathname') and 'no payment taken' in f.locator('#order-content').inner_text().lower())
    f=nav('/account/')
    record('Demo physical and membership subscription records are separate',f.locator('.subscription-card').count()==2)
    f.locator('[data-sub-action=pause]').first.click()
    record('Pause demo subscription',f.locator('.status-pill.paused').count()==1)
    f.locator('[data-sub-action=resume]').click()
    record('Resume demo subscription',f.locator('.status-pill.active').count()==2)
    before=f.locator('.subscription-card').first.inner_text()
    f.locator('[data-sub-action=skip]').first.click()
    record('Skip next renewal updates the displayed date',f.locator('.subscription-card').first.inner_text()!=before)
    f.locator('[data-sub-action=ask-cancel]').first.click()
    record('Cancellation asks for inline confirmation',f.locator('.subscription-confirm:visible').count()==1)
    f.locator('[data-sub-action=cancel]').first.click()
    record('Cancel demo subscription',f.locator('.status-pill.cancelled').count()==1)
    f=nav('/account/')
    record('Account controls persist after page change',f.locator('.status-pill.cancelled').count()==1)
    f=nav('/get-started/?programme=build&billing=year')
    f.locator('#next-step').click()
    record('Onboarding requires a stated goal',f.locator('.form-error').is_visible())
    f.locator('#first-name').fill('<script>alert(1)</script>')
    f.locator('#goal').select_option(label='Feel fitter')
    f.locator('#next-step').click()
    record('Programme deep link and annual billing carried into onboarding',f.locator('#programme').input_value()=='build' and f.locator('#billing').input_value()=='year')
    f.locator('#next-step').click()
    f.locator('input[name=coach][value=Steff]').check()
    f.locator('#finish-onboarding').click()
    p.wait_for_timeout(200);f=p.frames[1]
    record('Onboarding saves preferences and opens dashboard',p.evaluate('nfRoute.pathname')=='/dashboard/' and 'Explore Build.' in f.locator('main').inner_text())
    record('Names are escaped, not inserted as executable markup','<script>alert(1)</script>' in f.locator('h1').inner_text())
    record('No invented personalised targets',f.locator('.target-placeholder strong').all_text_contents()==['—','—'])
    record('Steff coach selection persists',f.locator('.dashboard-coach img').get_attribute('alt')=='Steff, AI coach')
    f=nav('/search/?q=flavour')
    record('Full-site search loads offline and returns matching pages',f.locator('.search-page-result').count()>=6)
    f.locator('#site-search').fill('no-such-item-ever')
    record('Full-site search has a usable empty state','Nothing' in f.locator('#search-status').inner_text())
    f=nav('/contact/')
    f.locator('#message').fill('Please help me choose a flavour.')
    f.locator('#contact-form button[type=submit]').click()
    record('Support draft is clearly not sent',f.locator('#contact-result').is_visible() and 'Not sent automatically' in f.locator('#prepared-message').input_value())
    f=nav('/programmes/?category=Gym')
    record('Gym filter includes home-or-gym programmes',f.locator('.programme-card:visible').count()==6)
    f=nav('/programmes/build/')
    record('Four-session programme has four displayed training slots',f.locator('.week-strip').inner_text().count('Training slot')==4)
    p.set_viewport_size({'width':390,'height':844})
    f=nav('/')
    f.locator('.menu-toggle').click()
    record('Mobile navigation opens inline',f.locator('#mobile-nav').is_visible())
    f.locator('.menu-toggle').press('Escape')
    record('Escape closes mobile navigation',not f.locator('#mobile-nav').is_visible())
    record('No runtime JS errors',not errors,'; '.join(errors))
    (R/'tests/browser-results.json').write_text(json.dumps(results,indent=2))
    print(f'{len(results)} browser interaction checks passed')
    b.close()
