import test from 'node:test';
import assert from 'node:assert/strict';
import {quoteCart,validateLine,addLine,safeStoredCart,unitPrice} from '../src/commerce.mjs';
const one={id:'plain-whey',qty:1,mode:'once',cadence:null};
const sub={...one,mode:'subscription',cadence:'4w'};
test('one-off total and delivery are computed from the catalogue',()=>{const q=quoteCart([one]);assert.equal(q.total,3295);assert.equal(q.recurring.length,0);});
test('subscription discount is rounded in integer pence',()=>{assert.equal(unitPrice(sub),2610);assert.equal(unitPrice({id:'shot-vanilla',qty:1,mode:'subscription',cadence:'4w'}),626);});
test('one-off extras do not repeat',()=>{const q=quoteCart([sub,{id:'shot-vanilla',qty:1,mode:'once',cadence:null}]);assert.equal(q.total,3700);assert.equal(q.recurring[0].total,3005);});
test('shipping threshold uses physical items only',()=>{const q=quoteCart([one,{id:'nufi-membership',qty:1,mode:'subscription',cadence:'year'}]);assert.equal(q.delivery,395);assert.equal(q.recurring[0].delivery,0);});
test('free shipping for enough physical merchandise',()=>assert.equal(quoteCart([{...one,qty:2}]).delivery,0));
test('digital-only baskets have no delivery',()=>assert.equal(quoteCart([{id:'high-protein-snacks',qty:1,mode:'once',cadence:null}]).delivery,0));
test('different renewal cadences remain separate',()=>{const q=quoteCart([sub,{id:'shot-chocolate',qty:2,mode:'subscription',cadence:'8w'},{id:'nufi-membership',qty:1,mode:'subscription',cadence:'month'}]);assert.deepEqual(q.recurring.map(r=>r.cadence),['4w','8w','month']);});
test('repeat line merges but one-off remains distinct',()=>{let l=addLine([sub],sub);assert.equal(l[0].qty,2);l=addLine(l,one);assert.equal(l.length,2);});
test('unknown product rejected',()=>assert.throws(()=>validateLine({...one,id:'bogus'})));
test('negative, fractional, zero and excessive quantities rejected',()=>{for(const qty of [-1,0,1.5,21,Infinity,'2'])assert.throws(()=>validateLine({...one,qty}));});
test('no implicit subscription or cadence',()=>{assert.throws(()=>validateLine({...one,mode:undefined}));assert.throws(()=>validateLine({...one,cadence:'4w'}));assert.throws(()=>validateLine({...sub,cadence:'month'}));});
test('books cannot silently become subscriptions',()=>assert.throws(()=>validateLine({...sub,id:'high-protein-kitchen'})));
test('only one member per membership line',()=>assert.throws(()=>validateLine({id:'nufi-membership',qty:2,mode:'subscription',cadence:'month'})));
test('client price tampering is ignored',()=>assert.equal(quoteCart([{...one,price:1,total:1}]).subtotal,2900));
test('invalid persisted cart entries are dropped',()=>assert.deepEqual(safeStoredCart([one,{id:'old-stock',qty:99},null]),[one]));
test('duplicate overflow is rejected',()=>assert.throws(()=>addLine([{...one,qty:20}],one)));
test('empty quote is truly zero',()=>{const q=quoteCart([]);assert.equal(q.total,0);assert.equal(q.delivery,0);});

test('monthly and annual memberships cannot be added together',()=>assert.throws(()=>addLine([{id:'nufi-membership',qty:1,mode:'subscription',cadence:'month'}],{id:'nufi-membership',qty:1,mode:'subscription',cadence:'year'})));
test('quote rejects direct multiple membership injection',()=>assert.throws(()=>quoteCart([{id:'nufi-membership',qty:1,mode:'subscription',cadence:'month'},{id:'nufi-membership',qty:1,mode:'subscription',cadence:'year'}])));
test('raw duplicates do not bypass quantity limits',()=>assert.throws(()=>quoteCart([one,one])));
test('stored conflicting membership is sanitised',()=>assert.equal(safeStoredCart([{id:'nufi-membership',qty:1,mode:'subscription',cadence:'month'},{id:'nufi-membership',qty:1,mode:'subscription',cadence:'year'}]).length,1));
