"""Read-only catalogue/book acceptance checks; no account or customer writes."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, os, subprocess
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'test-results'
OUT.mkdir(exist_ok=True)
MANIFEST = json.loads((ROOT / 'data/cookbooks/website-catalogue-manifest.json').read_text())
COLLECTION = json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {collectionBooks} from './src/collection-books.mjs'; console.log(JSON.stringify(collectionBooks));"],cwd=ROOT,text=True))
BASE = os.environ.get('NUFI_TEST_BASE_URL', 'http://127.0.0.1:4173').rstrip('/')
checks = []
def check(label, value):
    if not value: raise AssertionError(label)
    checks.append(label)
with sync_playwright() as p:
    opts = {'headless': True}
    if os.environ.get('CHROMIUM_PATH'): opts['executable_path'] = os.environ['CHROMIUM_PATH']
    elif Path('/usr/bin/chromium').exists(): opts['executable_path'] = '/usr/bin/chromium'
    browser = p.chromium.launch(**opts)
    page = browser.new_page(viewport={'width':1440,'height':1000})
    page.set_default_timeout(12000)
    errors=[]
    page.on('pageerror', lambda e: errors.append(str(e)))
    def visit(path):
        resp=page.goto(BASE+path,wait_until='domcontentloaded')
        check('HTTP page '+path, resp is not None and resp.status==200)
        check('One banner on '+path,page.locator('.launch-banner').count()==1)
        page.wait_for_timeout(180)
    visit('/recipes/')
    page.wait_for_function("expected => document.querySelectorAll('[data-recipe-grid] .food-card').length===expected", arg=MANIFEST['recipes'])
    check('Complete catalogue includes free recipes and account previews', page.locator('[data-recipe-grid] .food-card').count()==MANIFEST['recipes'])
    check('Source book selector is removed',page.locator('[data-recipe-book]').count()==0)
    check('Ordinary browsing has no original-collection restriction',page.locator('[data-original-recipes]').is_hidden())
    check('Catalogue heading is about food, not source volumes','books' not in page.locator('.food-intro .lead').inner_text())
    check('Cards do not advertise old source volumes','Volume ' not in page.locator('[data-recipe-grid]').inner_text())
    check('Free and complete collections are easy to find',page.locator('nav[aria-label="Recipe access"]').is_visible())
    page.locator('[data-access-free]').click()
    check('Visible free-recipes navigation opens the original 100',page.locator('[data-recipe-grid] .food-card').count()==100 and page.locator('[data-access-free]').get_attribute('aria-current')=='page')
    page.locator('[data-access-all]').click()
    check('Visible all-recipes navigation restores the full catalogue',page.locator('[data-recipe-grid] .food-card').count()==MANIFEST['recipes'] and page.locator('[data-access-all]').get_attribute('aria-current')=='page')
    for category,count in MANIFEST['categories'].items():
        page.locator('[data-recipe-category]').select_option(category)
        check(category+' filter matches catalogue', page.locator('[data-recipe-grid] .food-card').count()==count)
        check(category+' filter persists in URL','category='+category in page.url)
    page.locator('[data-recipe-category]').select_option('')
    page.locator('[data-recipe-search]').fill('vanilla berry')
    check('Recipes searchable by name',page.locator('[data-recipe-grid] .food-card').count()==1)
    page.locator('[data-recipe-search]').fill('zz-no-matching-recipe')
    check('Empty searches explain how to recover',page.locator('[data-no-recipes]').is_visible())
    page.locator('[data-recipe-search]').fill('')
    page.locator('[data-recipe-sort]').select_option('name')
    first_name=page.locator('[data-recipe-grid] .food-card h2').first.inner_text()
    page.reload(wait_until='domcontentloaded')
    page.wait_for_function("document.querySelector('[data-recipe-sort]').value==='name'")
    check('A to Z ordering survives reload',page.locator('[data-recipe-grid] .food-card h2').first.inner_text()==first_name)
    page.locator('[data-recipe-sort]').select_option('protein')
    proteins=page.locator('[data-recipe-grid] .food-protein').evaluate_all("els=>els.map(el=>parseFloat(el.textContent))")
    check('Protein ordering uses descending source estimates',proteins==sorted(proteins,reverse=True))
    source_book=MANIFEST['books'][1]
    visit('/recipes/?book='+source_book['id']+'&category=Breakfast&q=avocado&sort=name')
    check('Retired source-book links remove obsolete restriction','book=' not in page.url)
    check('Retired links preserve useful meal and search filters',page.locator('[data-recipe-category]').input_value()=='Breakfast' and page.locator('[data-recipe-search]').input_value()=='avocado' and page.locator('[data-recipe-sort]').input_value()=='name')
    check('Retired links return matching food',page.locator('[data-recipe-grid] .food-card').count()>0)
    visit('/recipes/?book=high-protein-kitchen')
    check('Flagship links retain the original 100 recipes',page.locator('[data-recipe-grid] .food-card').count()==100)
    check('Original-collection restriction is clearly labelled',page.locator('[data-original-recipes]').is_visible() and 'Original 100 recipes' in page.locator('[data-original-recipes]').inner_text())
    visit('/recipes/?book=high-protein-kitchen&category=Breakfast')
    check('Book category links filter the library',page.locator('[data-recipe-grid] .food-card').count()==22)
    page.locator('[data-all-recipes]').click()
    check('Full-collection link removes original-only restriction',page.locator('[data-recipe-grid] .food-card').count()==MANIFEST['categories']['Breakfast'] and 'book=' not in page.url)
    check('Reset keeps the chosen meal filter',page.locator('[data-recipe-category]').input_value()=='Breakfast')
    visit('/recipes/bacon-avocado-bowl/')
    check('Imported direct link shows the account preview',page.locator('[data-recipe-locked="bacon-avocado-bowl"]').is_visible())
    check('Unconfigured account access is explained','Account access coming soon' in page.locator('main').inner_text())
    check('Guest preview contains no ingredients or method',page.locator('[data-recipe-detail],[data-ingredients],[data-method]').count()==0)
    check('Guest preview has no cooking, editing or planning controls',page.locator('[data-recipe-yield],[data-cook-mode],[data-timer-start],a[href="/meal-planner/add/?recipe=bacon-avocado-bowl"],a[href="/recipe-edit/?recipe=bacon-avocado-bowl"]').count()==0)
    check('Guest preview exposes no Recipe structured data',all(json.loads(raw).get('@type')!='Recipe' for raw in page.locator('script[type="application/ld+json"]').all_text_contents()))
    restricted=page.request.get(BASE+'/api/recipes?scope=accessible')
    check('Anonymous full-catalogue API request is denied',restricted.status in [401,403,503])
    check('Denied API response contains no recipe payload','recipes' not in restricted.json() and 'recipe' not in restricted.json())
    if BASE.startswith('https://'):
        free=page.request.get(BASE+'/api/recipes?scope=free')
        check('Original 100 remain available from the free API',free.status==200 and len(free.json().get('recipes',[]))==100)
        check('Restricted API responses are not cached','no-store' in restricted.headers.get('cache-control',''))

    # A separate disposable browser workspace simulates a meal saved before access changed.
    legacy=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import * as C from './public/meal-core.mjs'; const state=C.newState(); const entry=C.addMeal(state,{recipeId:'tropical-overnight-oats',date:C.today(),slot:'Breakfast',servings:1}); entry.id='legacy-imported-meal'; entry.recipeId='bacon-avocado-bowl'; console.log(JSON.stringify({state,remoteVersion:0,pending:false}));"],cwd=ROOT,text=True))
    legacy_context=browser.new_context(viewport={'width':1440,'height':1000})
    legacy_context.add_init_script(script='if(location.origin==='+json.dumps(BASE)+'&&!localStorage.getItem("nufi-food-v1:guest")){localStorage.setItem("nufi-food-v1:guest",'+json.dumps(json.dumps(legacy))+');}')
    legacy_page=legacy_context.new_page()
    legacy_page.on('pageerror',lambda e:errors.append(str(e)))
    legacy_page.goto(BASE+'/meal-planner/',wait_until='domcontentloaded')
    locked_meal=legacy_page.locator('[data-locked-meal="legacy-imported-meal"]')
    locked_meal.wait_for(state='visible')
    check('Older saved meals remain in the plan with an access explanation','Account access coming soon' in locked_meal.inner_text())
    check('Unavailable saved meal cannot be newly logged',locked_meal.locator('a[href*="/meal-planner/log/"]').count()==0)
    check('Saved meal can still be moved, removed or swapped',locked_meal.locator('a[href*="/meal-planner/edit/"]').count()==1)
    check('Opening a plan preserves the older entry',legacy_page.evaluate('JSON.parse(localStorage.getItem("nufi-food-v1:guest")).state.plans[0].entries[0].recipeId')=='bacon-avocado-bowl')
    legacy_page.goto(BASE+'/shopping-list/',wait_until='domcontentloaded')
    legacy_page.locator('[data-shopping-incomplete]').wait_for(state='visible')
    check('Shopping list explains unavailable saved ingredients','Shopping list incomplete' in legacy_page.locator('[data-shopping-incomplete]').inner_text())
    check('Unavailable ingredients are never presented as a complete shopping list',legacy_page.locator('[data-shop-key]').count()==0)
    legacy_page.goto(BASE+'/meal-planner/edit/?entry=legacy-imported-meal',wait_until='domcontentloaded')
    legacy_page.locator('[data-meal-form] [name="slot"]').select_option('Lunch')
    legacy_page.locator('[data-meal-form] button[type="submit"]').click()
    legacy_page.wait_for_url(lambda url:'/meal-planner/?date=' in url)
    moved=legacy_page.evaluate('JSON.parse(localStorage.getItem("nufi-food-v1:guest")).state.plans[0].entries[0]')
    check('An older locked meal can move without losing its reference',moved['id']=='legacy-imported-meal' and moved['recipeId']=='bacon-avocado-bowl' and moved['slot']=='Lunch')
    legacy_page.goto(BASE+'/meal-planner/edit/?entry=legacy-imported-meal',wait_until='domcontentloaded')
    legacy_page.locator('[data-meal-form] [name="recipeId"]').select_option('tropical-overnight-oats')
    legacy_page.locator('[data-meal-form] button[type="submit"]').click()
    legacy_page.wait_for_url(lambda url:'/meal-planner/?date=' in url)
    swapped=legacy_page.evaluate('JSON.parse(localStorage.getItem("nufi-food-v1:guest")).state.plans[0].entries[0]')
    check('An older locked meal can be swapped for a free recipe',swapped['id']=='legacy-imported-meal' and swapped['recipeId']=='tropical-overnight-oats')
    legacy_page.goto(BASE+'/shopping-list/',wait_until='domcontentloaded')
    legacy_page.locator('[data-shop-key]').first.wait_for(state='visible')
    check('Shopping list becomes complete after swapping to a free recipe',legacy_page.locator('[data-shopping-incomplete]').count()==0)
    legacy_context.close()
    for path,count in [('/recipes/vanilla-berry-smoothie/',2),('/recipes/omelette-muffins/',6),('/recipes/chocolate-fudge-bars/',6)]:
        visit(path)
        check('Complete method '+path,page.locator('[data-method] li').count()==count)
    check('Missing original photo explicit',page.locator('.recipe-no-photo').count()>0)
    visit('/recipes/fragrant-spiced-chickpea-hash/')
    note=page.locator('.source-review')
    check('Source review prompt is visible',note.locator('summary').is_visible())
    if note.get_attribute('open') is None:
        note.locator('summary').click()
    check('Printed serving conflict explained','Source serving conflict' in note.inner_text())
    visit('/shop/high-protein-kitchen/')
    check('Book uses supplied cover',page.locator('.cookbook-cover img').get_attribute('src')=='/assets/cookbook/high-protein-kitchen-cover.webp')
    check('143-page digital edition described','143 pages' in page.locator('body').inner_text())
    check('Price pending, not invented','Price to be announced' in page.locator('body').inner_text())
    check('Book cannot be added at an unapproved price',page.locator('[data-add-product],[data-add-to-cart]').count()==0)
    check('Paid PDF is not a public download',page.locator('a[href$=".pdf"]').count()==0)
    check('Book retains launch date','1 November 2026' in page.locator('body').inner_text())
    for width in [390,760,1024,1440]:
        page.set_viewport_size({'width':width,'height':900})
        check('Book layout no overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.evaluate('Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>null)}))')
        check('Book cover/images load '+str(width),page.evaluate('[...document.images].filter(i=>i.getAttribute("src")).every(i=>i.complete&&i.naturalWidth>0)'))
        if width in [390,1440]:page.screenshot(path=str(OUT/f'cookbook-{width}.png'),full_page=True)
    visit('/shop/')
    check('Book listed in shop',page.locator('a[href="/shop/high-protein-kitchen/"]').count()>0)
    visit('/recipe-books/')
    check('Book listed in Recipe Books',page.locator('a[href="/shop/high-protein-kitchen/"]').count()>0)
    check('Eight actual books in the collection',page.locator('.product-card[data-category="books"]').count()==8)
    check('Retired book concepts and prices are absent','Digital book concept' not in page.locator('main').inner_text() and '£14.95' not in page.locator('main').inner_text())
    for width in [390,1440]:
        page.set_viewport_size({'width':width,'height':900})
        check('Collection grid no overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.evaluate('Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>null)}))')
        check('Collection cover images load '+str(width),page.locator('.actual-book-art img').evaluate_all('els=>els.length===8&&els.every(i=>i.complete&&i.naturalWidth>0)'))
        page.screenshot(path=str(OUT/f'book-collection-{width}.png'),full_page=True)
    for book in COLLECTION:
        visit('/shop/'+book['id']+'/')
        main=page.locator('main')
        check('New book title '+book['id'],page.locator('#collection-book-title').inner_text()==book['title'])
        check('Actual collection cover '+book['id'],page.locator('.cookbook-cover img').get_attribute('src')==book['image'])
        check('Final recipe and page counts '+book['id'],page.locator('.cookbook-facts dd').all_text_contents()==[str(book['recipeCount']),str(book['pageCount'])+' pages','Digital PDF'])
        check('Coming-soon status '+book['id'],'Coming soon' in page.locator('.cookbook-buybox').inner_text() and 'Price to be announced' in page.locator('.cookbook-order-status').inner_text())
        check('No checkout or PDF exposure '+book['id'],main.locator('#product-form,[data-add-product],[data-add-to-cart],a[href$=".pdf"]').count()==0)
        check('No hardback or invented book launch date '+book['id'],'hardback' not in main.inner_text().lower() and '1 November' not in main.inner_text())
        check('New book chapter outline '+book['id'],page.locator('.collection-chapters li').count()==len(book['chapters']))
        for width in [390,1440]:
            page.set_viewport_size({'width':width,'height':900})
            check('New book no overflow '+book['id']+' '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            page.wait_for_function('document.querySelector(".cookbook-cover img").complete&&document.querySelector(".cookbook-cover img").naturalWidth>0')
        if book['id'] in ['breakfast-sorted','more-plants-please']:
            page.screenshot(path=str(OUT/(book['id']+'-desktop.png')),full_page=True)
    for old,new in [('high-protein-smoothies','blend-and-go'),('high-protein-fakeaways','big-night-in'),('high-protein-snacks','snack-happy')]:
        rules=json.loads((ROOT/'vercel.json').read_text())['redirects']
        check('Legacy book redirect configured '+old,any(r.get('source')=='/shop/'+old+'/' and r.get('destination')=='/shop/'+new+'/' and r.get('permanent') for r in rules))
        if BASE.startswith('https://'):
            visit('/shop/'+old+'/')
            check('Legacy book redirects to new title '+old,page.url.endswith('/shop/'+new+'/'))
    check('No JavaScript errors',not errors)
    browser.close()
report={'mode':BASE,'passed':len(checks),'checks':checks,'errors':errors}
(OUT/('cookbook-production.json' if BASE.startswith('https://') else 'cookbook-browser.json')).write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2))
