import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {RECIPES,COOKBOOK_SOURCE,RECIPE_BY_ID} from '../public/recipes-data.mjs';
import * as C from '../public/meal-core.mjs';
import {ingredientText,timeLabel,sourceHint} from '../public/recipe-display.mjs';
import {products} from '../src/data.mjs';
import {quoteCart,money} from '../src/commerce.mjs';
import {bookPage} from '../src/cookbook-pages.mjs';
const source=JSON.parse(await readFile(new URL('../data/cookbooks/high-protein-kitchen.json',import.meta.url),'utf8'));
const hash=x=>createHash('sha256').update(x).digest('hex');
const byNumber=n=>RECIPES.find(r=>r.sourceRecipeNumber===n);
test('all 100 source recipes are mirrored without silent edits',()=>assert.deepEqual({source:COOKBOOK_SOURCE,recipes:RECIPES},source));
test('five original cookbook category counts are retained',()=>assert.deepEqual(Object.fromEntries(['Breakfast','Lunch','Dinner','Snacks','Drinks'].map(c=>[c,RECIPES.filter(r=>r.category===c).length])),{Breakfast:22,Lunch:24,Dinner:25,Snacks:14,Drinks:15}));
test('source recipe numbers run from 1 to 100 with unique IDs',()=>{assert.equal(new Set(RECIPES.map(r=>r.id)).size,100);assert.deepEqual(RECIPES.map(r=>r.sourceRecipeNumber),Array.from({length:100},(_,i)=>i+1));});
test('source method and ingredient inventory is complete',()=>{assert.equal(RECIPES.reduce((a,r)=>a+r.ingredients.length,0),1038);assert.equal(RECIPES.reduce((a,r)=>a+r.steps.length,0),575);});
test('all recipes pass the same validator used for private account sync',()=>{for(const r of RECIPES){const valid=C.recipe(r);assert.equal(valid.name,r.name);assert.deepEqual(valid.nutrition,r.nutrition);}});
test('original yield displays ingredient wording exactly as printed',()=>{for(const r of RECIPES)for(const i of C.scaledIngredients(r,r.servings))assert.equal(ingredientText(i),i.sourceText);});
test('all original nutrition values are estimates, not recalculated claims',()=>{for(const r of RECIPES){assert.equal(r.nutritionStatus,'source-estimate');assert.match(r.nutritionSource,/estimates, not independently analysed/);assert.equal(r.sourceSha256,COOKBOOK_SOURCE.sha256);}});
test('missing total times stay null instead of fictional zero-minute cooking',()=>{for(const r of RECIPES){assert.equal(r.prepMinutes,null);assert.equal(r.cookMinutes,null);assert.equal(r.waitMinutes,null);assert.equal(timeLabel(r),'Timings in the method');}});
test('ranges and compound package amounts do not select an arbitrary number',()=>{for(const r of RECIPES)for(const i of r.ingredients.filter(i=>['range','compound'].includes(i.scalingMode))){assert.equal(i.quantity,null);assert.equal(ingredientText(i),i.sourceText);assert.match(sourceHint({...i,scaleFactor:2}),/Amount kept as printed/);}});
test('recipe per-ball and per-muffin bases are not divided twice',()=>{assert.equal(C.portionNutrition(byNumber(72),1).protein,7);assert.equal(byNumber(72).servings,7);assert.equal(C.portionNutrition(byNumber(3),1).protein,10);assert.equal(byNumber(3).servings,9);});
test('chickpea-hash serving conflict is preserved with an explicit review note',()=>{const r=byNumber(14);assert.equal(r.servings,1);assert.match(r.steps[5],/two plates/);assert.match(r.notes,/Source serving conflict/);});
test('printed 200g versus 14 oz conflict is not silently converted',()=>{const i=byNumber(26).ingredients.find(i=>i.sourceText.includes('200g (14 oz)'));assert.equal(i.quantity,200);assert.equal(i.unit,'g');assert.match(i.note,/14 oz/);assert.match(byNumber(26).notes,/Source measure conflict/);});
test('leftover batch toppings retain both the full ingredient batch and serving caveat',()=>{for(const n of [10,13,73,84])assert.match(byNumber(n).notes,/batch/);});
test('method discrepancies are retained for owner review, not filled from generic recipes',()=>{assert.match(byNumber(3).notes,/fill the muffin tin/);assert.match(byNumber(50).notes,/both steps 4 and 5/);assert.match(byNumber(76).notes,/dark chocolate/);});
test('six pre-existing recipe IDs remain stable for saved plans',()=>{const expected={5:'tropical-overnight-oats',11:'blueberry-lemon-oats',41:'greek-chicken-salad',67:'salmon-lime-rice-bowl',71:'bean-chickpea-chilli',72:'chocolate-orange-energy-balls'};for(const [n,id]of Object.entries(expected))assert.equal(byNumber(Number(n)).id,id);});
test('saving an unchanged imported recipe does not invalidate nutrition due to provenance metadata',()=>{const s=C.newState();const r=C.saveRecipe(s,C.clone(byNumber(5)));assert.equal(r.nutritionStatus,'source-estimate');assert.equal(r.nutrition.protein,29);});
test('actual ingredient changes invalidate nutrition while historical logs stay immutable',()=>{const s=C.newState('2026-09-14'),r=byNumber(5);const e=C.addMeal(s,{recipeId:r.id,date:'2026-09-14',slot:'Breakfast',servings:1});C.logMeal(s,e.id,1,'2026-09-14');const changed=C.clone(r);changed.ingredients[0].quantity=90;C.saveRecipe(s,changed);assert.equal(C.findRecipe(s,r.id).nutritionStatus,'review-needed');assert.equal(s.logs[0].nutrition.protein,29);});
test('a personal nutrition override remains authoritative when catalogue expands',()=>{const s=C.newState(),r=C.clone(byNumber(5));r.nutrition.protein=35;C.saveRecipe(s,r,true);assert.equal(C.allRecipes(s).length,100);assert.equal(C.findRecipe(C.validateState(s),r.id).nutrition.protein,35);});
test('drinks can be planned and logged without relabelling them snacks',()=>{const s=C.newState('2026-09-14'),r=byNumber(100);const e=C.addMeal(s,{recipeId:r.id,date:'2026-09-14',slot:'Drinks',servings:1});C.logMeal(s,e.id,1,'2026-09-14');assert.equal(C.validateState(s).logs[0].slot,'Drinks');});
test('99 supplied photographs exist; recipe 85 never substitutes a stock image',async()=>{assert.equal(RECIPES.filter(r=>r.image).length,99);assert.equal(byNumber(85).image,'');for(const r of RECIPES.filter(r=>r.image))assert.ok((await stat(new URL('../public'+r.image,import.meta.url))).size>1000);});
test('source image audit fingerprints match every extracted photograph',async()=>{const audit=JSON.parse(await readFile(new URL('../data/cookbooks/import-audit.json',import.meta.url),'utf8'));for(const a of audit.filter(a=>a.imageSha256)){const data=await readFile(new URL('../public'+RECIPE_BY_ID[a.id].image,import.meta.url));assert.equal(hash(data),a.imageSha256,a.name);}});
test('book uses supplied cover, 100 recipes, and no invented approved selling price',()=>{const b=products.find(p=>p.id==='high-protein-kitchen');assert.equal(b.price,null);assert.equal(b.art,'published-book');assert.match(b.image,/high-protein-kitchen-cover.webp$/);assert.equal(money(b.price),'Price to be announced');assert.match(bookPage(),/143 pages/);assert.match(bookPage(),/Price to be announced/);});
test('unapproved book price cannot be interpreted as a free or paid checkout item',()=>{assert.throws(()=>quoteCart([{id:'high-protein-kitchen',quantity:1,mode:'once'}]),/not yet priced/);});
test('book page never exposes the entire paid PDF as a public download',()=>{assert.doesNotMatch(bookPage(),/href=["'][^"']*\.pdf/i);assert.match(bookPage(),/1 November 2026/);});
