import test from 'node:test';import assert from 'node:assert/strict';
import {LAUNCH,countdownParts,freeMonthEndsAt,launchState} from '../public/launch-config.mjs';
import {BASES,validateAnswers,recommend} from '../public/programme-finder.mjs';
import {compileLaunchLayout,accentFor} from '../src/launch-layout.mjs';
import {createLeadHandler,validateLead} from '../api/leads.js';
const answers={goal:'foundation',experience:'returning',equipment:['weights','bodyweight'],days:'3',minutes:'30',focus:['arms','chest','shoulders'],barrier:'consistency'};
const payload={firstName:'James',email:'  PERSON@example.com ',answers,source:'programme-finder',marketing:false,requestId:'abcd1234-abcd-abcd-abcd-123456789abc',botToken:'verified-test-token'};
const env={GHL_PRIVATE_TOKEN:'test-only-not-a-real-token',GHL_LOCATION_ID:'test-location',GHL_PROGRAMME_FIELD_ID:'test-programme',GHL_QUIZ_FIELD_ID:'test-quiz',SITE_URL:'https://nutrition.fitness',TURNSTILE_SECRET_KEY:'test-secret',TURNSTILE_SITE_KEY:'test-site'};
function response(){return {code:0,data:null,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(v){this.data=v;}};}
const request=(body=payload)=>({method:'POST',headers:{origin:'https://nutrition.fitness','content-type':'application/json'},body});
test('launch date is exactly the agreed fixed instant',()=>assert.equal(LAUNCH.at,'2026-12-01T09:00:00.000Z'));
test('countdown rolls days/hours/minutes correctly',()=>assert.deepEqual(countdownParts(Date.parse(LAUNCH.at)-((2*24+3)*60+4)*60000),{days:2,hours:3,minutes:4,reached:false}));
test('countdown never goes negative',()=>assert.deepEqual(countdownParts(Date.parse(LAUNCH.at)+99999),{days:0,hours:0,minutes:0,reached:true}));
test('release requires date and an explicit live state',()=>{assert.equal(launchState(Date.parse(LAUNCH.at)-1,true),'prelaunch');assert.equal(launchState(Date.parse(LAUNCH.at),false),'awaiting-release');assert.equal(launchState(Date.parse(LAUNCH.at),true),'live');});
test('invalid timestamps are rejected',()=>assert.throws(()=>countdownParts(NaN)));
test('free month starts at activation and lasts a calendar month',()=>assert.equal(freeMonthEndsAt('2026-12-04T12:15:00Z'),'2027-01-04T12:15:00.000Z'));
test('month expiry clamps shorter months',()=>assert.equal(freeMonthEndsAt('2027-01-31T12:15:00Z'),'2027-02-28T12:15:00.000Z'));
test('free month cannot activate before launch',()=>assert.throws(()=>freeMonthEndsAt('2026-11-30T23:59:59Z')));
test('all agreed bases are represented',()=>assert.deepEqual(Object.keys(BASES),['core','build','lean','fit','run','swim','bike']));
test('multiple dot-appended focus areas survive',()=>assert.equal(recommend(answers).name,'core.arms.chest.shoulders'));
test('build is a distinct base',()=>assert.equal(recommend({...answers,goal:'muscle'}).name,'build.arms.chest.shoulders'));
test('user base override remains authoritative',()=>{const x=recommend(answers,'build');assert.equal(x.base,'build');assert.equal(x.suggested,'core');assert.equal(x.overridden,true);});
test('missing pool is explained rather than silently changing the goal',()=>{const r=recommend({...answers,goal:'swimming'});assert.equal(r.base,'swim');assert.ok(r.warnings.some(x=>x.includes('pool')));});
test('incompatible add-ons are explicitly reported',()=>{const r=recommend({...answers,goal:'fitness'});assert.deepEqual(r.notAdded,['arms','chest','shoulders']);assert.equal(r.name,'fit');});
test('unknown/invalid quiz inputs cannot inject programme values',()=>{assert.throws(()=>recommend({...answers,goal:'<script>'}));assert.throws(()=>recommend(answers,'__proto__'));assert.throws(()=>validateAnswers({...answers,focus:['invalid']}));});
test('missing answers rejected and optional focus accepted',()=>{assert.throws(()=>recommend({}));assert.equal(recommend({...answers,focus:[]}).name,'core');});
test('lead validation normalises email, keeps optional consent false',()=>{const r=validateLead(payload);assert.equal(r.email,'person@example.com');assert.equal(r.marketing,false);});
test('lead rejects HTML names and nonboolean consent',()=>{assert.throws(()=>validateLead({...payload,firstName:'<script>'}));assert.throws(()=>validateLead({...payload,marketing:'false'}));});
test('accent varies without replacing homepage plum',()=>{assert.equal(accentFor('/'),'plum');assert.equal(accentFor('/recipes/'),'green');assert.equal(accentFor('/courses/'),'terracotta');});
test('compiler fails loudly on unknown base header',()=>assert.throws(()=>compileLaunchLayout('<html></html>','/')));
test('missing CRM configuration never reports a signup success',async()=>{const res=response();await createLeadHandler({env:{}})(request(),res);assert.equal(res.code,503);assert.ok(!res.data.status);});
test('cross-origin signup rejected before remote requests',async()=>{const res=response();const req=request();req.headers.origin='https://not-the-site.invalid';await createLeadHandler({env,fetchImpl:()=>{throw new Error('Should not run')}})(req,res);assert.equal(res.code,403);});
test('successful signup saves computed result without replacing tags/DND/trial status',async()=>{const calls=[];const fetchImpl=async(url,opts)=>{calls.push({url,opts});if(url.includes('siteverify'))return new Response(JSON.stringify({success:true,hostname:'nutrition.fitness',action:'nufi-signup'}));if(url.endsWith('/upsert'))return new Response(JSON.stringify({contact:{id:'test-contact'}}));return new Response('{}');};const res=response();await createLeadHandler({env,fetchImpl,now:()=>Date.parse('2026-09-16T15:00:00Z')})(request(),res);assert.equal(res.code,200);assert.equal(res.data.status,'reserved');const up=JSON.parse(calls[1].opts.body);assert.equal(up.email,'person@example.com');for(const key of ['tags','dnd','dndSettings','source'])assert.equal(up[key],undefined);assert.equal(up.customFields[0].fieldValue,'core.arms.chest.shoulders');assert.ok(calls[2].opts.body.includes('email-optin-v1'));assert.deepEqual(JSON.parse(calls[3].opts.body).tags,['nufi-programme-finder','nufi-free-month-eligible']);assert.ok(!JSON.stringify(res.data).includes('test-contact'));});
test('CRM rejection cannot create a fake reservation',async()=>{const res=response();await createLeadHandler({env,fetchImpl:async url=>url.includes('siteverify')?new Response(JSON.stringify({success:true,hostname:'nutrition.fitness',action:'nufi-signup'})):new Response('{}',{status:401})})(request(),res);assert.equal(res.code,502);assert.equal(res.data.status,undefined);});
test('failed or wrong-host bot check never contacts CRM',async()=>{let count=0;const res=response();await createLeadHandler({env,fetchImpl:async()=>{count++;return new Response(JSON.stringify({success:true,hostname:'wrong.invalid',action:'nufi-signup'}));}})(request(),res);assert.equal(res.code,400);assert.equal(count,1);});
