import {state,launchDate,workstreams,phases,esc,ws,statusLabel,doneLike,formatDate,daysUntil,pct,taskProgress,dueClass} from './store.js';

export function renderOverview(root,openTask,setView){
 const total=state.tasks.length,done=state.tasks.filter(doneLike).length,p0=state.tasks.filter(t=>t.priority==='P0'&&!doneLike(t)),overdue=state.tasks.filter(t=>!doneLike(t)&&daysUntil(t.due)<0),waiting=state.tasks.filter(t=>['waiting','changes','submitted'].includes(t.status)),remain=Math.max(0,daysUntil(launchDate));
 const blockers=[...p0].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,8);
 root.innerHTML=`<div class="metrics"><div class="metric countdown"><span>Days to launch</span><strong>${remain}</strong></div><div class="metric red"><span>P0 blockers</span><strong>${p0.length}</strong></div><div class="metric plum"><span>Overall complete</span><strong>${pct(done,total)}%</strong></div><div class="metric"><span>Overdue</span><strong>${overdue.length}</strong></div><div class="metric"><span>Waiting / review</span><strong>${waiting.length}</strong></div></div>
 <div class="grid-2"><div class="panel"><div class="panel-head"><div><h2>Launch programme</h2><p>${done} of ${total} tasks approved or done</p></div><button class="link-button" data-go="tasks">Open register</button></div><div class="panel-body"><div class="progress-track"><div class="progress-bar" style="width:${pct(done,total)}%"></div></div><div class="progress-meta"><span>${pct(done,total)}% complete</span><span>${total-done} remaining</span></div><div class="workstream-list">${workstreams.map(w=>{const list=state.tasks.filter(t=>t.workstream===w.id),complete=list.filter(doneLike).length;return `<div class="workstream-row"><div><strong>${esc(w.name)}</strong><small>${complete}/${list.length} complete · ${list.filter(t=>t.priority==='P0'&&!doneLike(t)).length} open P0</small></div><div class="mini-progress"><i style="width:${pct(complete,list.length)}%"></i></div></div>`}).join('')}</div></div></div>
 <div class="panel"><div class="panel-head"><div><h2>Immediate P0 blockers</h2><p>Work these before nice-to-have work.</p></div></div><div class="panel-body"><div class="blocker-list">${blockers.length?blockers.map(t=>`<div class="blocker" data-task="${t.id}"><div class="row"><strong>${t.id} · ${esc(t.title)}</strong><span class="badge p0">P0</span></div><p>${formatDate(t.due)} · ${esc(t.owner)} · ${statusLabel(t.status)}</p></div>`).join(''):'<div class="empty">No open P0 blockers.</div>'}</div></div></div></div>
 <div class="grid-2"><div class="panel"><div class="panel-head"><div><h2>Next 7 days</h2><p>Anything due within a week and not complete.</p></div></div><div class="panel-body quick-list">${quickDue(7)}</div></div><div class="panel"><div class="panel-head"><div><h2>Current phase</h2><p>Work backwards from the next gate.</p></div></div><div class="panel-body">${currentPhaseCard()}</div></div></div>`;
 root.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('click',()=>openTask(el.dataset.task)));
 root.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.go)));
}
function quickDue(days){const list=state.tasks.filter(t=>!doneLike(t)&&daysUntil(t.due)<=days).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,12);return list.length?list.map(t=>`<div class="quick-item"><button data-task="${t.id}"><strong>${t.id}</strong> ${esc(t.title)}</button><span class="${dueClass(t)}">${formatDate(t.due)}</span></div>`).join(''):'<div class="empty">Nothing due in this window.</div>'}
function currentPhaseCard(){const today=new Date().toISOString().slice(0,10),p=phases.find(x=>today>=x.start&&today<=x.end)||phases.find(x=>today<x.start)||phases.at(-1),list=state.tasks.filter(t=>t.phase===p.id);return `<span class="badge p1">${p.dates}</span><h2 style="margin:10px 0 6px">${p.name}</h2><p style="margin:0 0 14px;color:var(--muted)">${esc(p.objective)}</p><div class="progress-track"><div class="progress-bar" style="width:${taskProgress(list)}%"></div></div><div class="progress-meta"><span>${taskProgress(list)}% complete</span><span>${list.filter(t=>t.priority==='P0'&&!doneLike(t)).length} open P0</span></div>`}

export function renderTasks(root,openTask){
 root.innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Master launch tracker</h2><p>${state.tasks.length} tasks · owner, deadline, dependency and done criteria.</p></div></div><div class="panel-body"><div class="filters"><input id="f-search" placeholder="Search ID or task"><select id="f-ws"><option value="">All workstreams</option>${workstreams.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><select id="f-priority"><option value="">All priorities</option><option>P0</option><option>P1</option><option>P2</option></select><select id="f-status"><option value="">All statuses</option>${['todo','in_progress','waiting','submitted','changes','approved','done'].map(s=>`<option value="${s}">${statusLabel(s)}</option>`).join('')}</select><select id="f-owner"><option value="">All owners</option>${state.team.map(n=>`<option>${esc(n.name)}</option>`).join('')}</select></div><div style="overflow:auto"><table class="task-table"><thead><tr><th>ID</th><th>Task</th><th>Priority</th><th>Owner</th><th>Due</th><th>Status</th></tr></thead><tbody id="task-rows"></tbody></table></div></div></div>`;
 const redraw=()=>renderRows(root,openTask);root.querySelectorAll('.filters input,.filters select').forEach(x=>x.addEventListener('input',redraw));redraw();
}
function renderRows(root,openTask){const g=id=>root.querySelector(id),q=g('#f-search').value.trim().toLowerCase(),fw=g('#f-ws').value,fp=g('#f-priority').value,fs=g('#f-status').value,fo=g('#f-owner').value;const list=state.tasks.filter(t=>(!q||(t.id+' '+t.title).toLowerCase().includes(q))&&(!fw||t.workstream===fw)&&(!fp||t.priority===fp)&&(!fs||t.status===fs)&&(!fo||t.owner===fo)).sort((a,b)=>a.due.localeCompare(b.due)||a.id.localeCompare(b.id));g('#task-rows').innerHTML=list.map(t=>`<tr data-task="${t.id}"><td class="task-id">${t.id}</td><td class="task-name"><strong>${esc(t.title)}</strong><small>${esc(ws(t.workstream)?.name||'')}</small></td><td><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span></td><td>${esc(t.owner)}</td><td class="${dueClass(t)}">${formatDate(t.due)}</td><td><span class="badge status-${t.status}">${statusLabel(t.status)}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No tasks match those filters.</td></tr>';g('#task-rows').querySelectorAll('[data-task]').forEach(r=>r.addEventListener('click',()=>openTask(r.dataset.task)))}

export function renderTimeline(root){root.innerHTML=`<div class="section-title"><div><h2>45-day launch sequence</h2><p>Each gate reduces uncertainty before the next phase starts.</p></div></div><div class="phase-board">${phases.map(p=>{const list=state.tasks.filter(t=>t.phase===p.id),openP0=list.filter(t=>t.priority==='P0'&&!doneLike(t)).length;return `<div class="phase"><div class="phase-head"><div><span class="task-id">${p.dates}</span><h3>${p.name}</h3><p>${esc(p.objective)}</p></div><div class="phase-stats"><strong>${taskProgress(list)}%</strong>${list.length} tasks · ${openP0} open P0</div></div><div class="progress-track" style="margin-top:14px"><div class="progress-bar" style="width:${taskProgress(list)}%"></div></div></div>`}).join('')}</div>`}

export function renderDecisions(root,save){root.innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Decisions register</h2><p>Stops locked decisions quietly reopening and creating scope creep.</p></div><button class="primary" id="add-decision">+ Decision</button></div><div class="panel-body"><div class="decision-list">${state.decisions.map(d=>`<div class="decision"><div class="decision-top"><div><span class="task-id">${d.id} · ${formatDate(d.date)}</span><h3>${esc(d.title)}</h3></div><span class="badge status-approved">${esc(d.status)}</span></div><p>${esc(d.decision)}</p><small>Owner: ${esc(d.owner)}</small></div>`).join('')}</div></div></div>`;root.querySelector('#add-decision').addEventListener('click',()=>{const title=prompt('Decision title');if(!title)return;const decision=prompt('What was decided?');if(!decision)return;state.decisions.unshift({id:`DEC-${String(state.decisions.length+1).padStart(3,'0')}`,date:new Date().toISOString().slice(0,10),title,decision,owner:'James',status:'locked'});save();renderDecisions(root,save)})}

export function renderTeam(root,save){const counts=name=>({all:state.tasks.filter(t=>t.owner===name).length,p0:state.tasks.filter(t=>t.owner===name&&t.priority==='P0'&&!doneLike(t)).length});root.innerHTML=`<div class="panel"><div class="panel-head"><div><h2>People & ownership</h2><p>Assign accountable owners. “Everyone” is not an owner.</p></div><button class="primary" id="add-person">+ Person</button></div><div class="panel-body"><div class="team-grid">${state.team.map(p=>{const c=counts(p.name);return `<div class="person"><div class="avatar">${esc(p.name.slice(0,1).toUpperCase())}</div><h3>${esc(p.name)}</h3><p>${esc(p.role)}</p><p><strong>${c.all}</strong> assigned · <strong>${c.p0}</strong> open P0</p></div>`}).join('')}</div></div></div>`;root.querySelector('#add-person').addEventListener('click',()=>{const name=prompt('Name');if(!name)return;const role=prompt('Role / responsibility')||'Team member';state.team.push({id:'person-'+Date.now(),name,role});save();renderTeam(root,save)})}
