import {t} from './seed-core.js';
export const tasks=[
// Website, Shop & Customer Journey
t('NF-039','website','Approve final website information architecture','P0','core','2026-09-23','Lock core pages, hierarchy and navigation around Explain → Diagnose → Recommend → Sell → Support.','Final sitemap is approved and every launch offer has a clear home.',['NF-001']),
t('NF-040','website','Complete NUFI and NUFI+ sales pages','P0','sellable','2026-10-02','Finish proposition, inclusions, pricing logic, proof and calls to action.','A first-time visitor can understand NUFI, who it is for and the next step.',['NF-005','NF-039']),
t('NF-041','website','Complete programme sales pages','P0','sellable','2026-10-02','Create individual pages for each launch programme with audience, outcome, structure, equipment and CTA.','Every launch programme is clearly sellable without relying on a salesperson.',['NF-002','NF-021','NF-039']),
t('NF-042','website','Complete supplement and product pages','P0','sellable','2026-10-03','Publish accurate product pages using approved SKUs, pricing, pack shots and compliant copy.','Every launch physical product can be understood and added to basket with correct variant/SKU.',['NF-030','NF-033','NF-034']),
t('NF-043','website','Configure one-off products, subscriptions and bundles in checkout','P0','sellable','2026-10-04','Implement one-off purchases, recurring products and approved bundles.','Test customer can purchase each launch offer at the correct price and cadence.',['NF-005','NF-006','NF-030']),
t('NF-044','website','Configure shipping, stock and customer account rules','P0','sellable','2026-10-04','Configure shipping methods, stock behaviour, order account view, pause/cancel rules and out-of-stock handling.','Physical and subscription orders behave correctly end to end.',['NF-038','NF-043']),
t('NF-045','website','Complete transactional email flows','P0','sales','2026-10-08','Create purchase, subscription, renewal, failed payment, dispatch and account emails.','All transactional messages trigger with correct customer/order data.',['NF-043']),
t('NF-046','website','Complete programme finder quiz and recommendations','P0','sales','2026-10-07','Connect goal, experience, equipment, lifestyle and nutrition answers to a clear recommendation and next step.','Quiz produces explainable programme, bolt-on and relevant product recommendations without dead ends.',['NF-002','NF-006']),
t('NF-047','website','Complete technical SEO baseline','P1','sales','2026-10-10','Implement titles, descriptions, canonicals, sitemap, robots, structured data, internal linking, alt text and search console setup.','Launch pages are crawlable/indexable as intended and core technical checks pass.',['NF-039']),
t('NF-048','website','Run checkout and account journey tests','P0','uat','2026-10-14','Test new, returning, subscription, physical-only and failure-state customers.','All primary purchase/account journeys pass with defects logged and owned.',['NF-043','NF-044','NF-045']),
// Marketing & Sales Engine
t('NF-049','marketing','Approve acquisition and lifecycle architecture','P0','core','2026-09-25','Define Acquisition → Conversion → Onboarding → Retention and channel responsibilities.','One funnel map connects ads/content, quiz, offer, checkout, onboarding and retention.',['NF-001']),
t('NF-050','marketing','Configure GoHighLevel launch CRM','P0','sales','2026-10-06','Set up contacts, pipelines, tags, fields, forms, opportunities and attribution.','Lead and customer records move through the correct lifecycle with source data preserved.',['NF-049']),
t('NF-051','marketing','Build prospect nurture sequence','P1','sales','2026-10-09','Create welcome, education, objection, proof, recommendation and conversion emails.','Prospects entering the funnel receive the intended timed sequence and correct links.',['NF-050']),
t('NF-052','marketing','Build customer onboarding sequence','P0','sales','2026-10-09','Connect order confirmation, NUFI activation, programme, nutrition, supplement and progress communications.','A new customer knows exactly what to do next from purchase onward.',['NF-027','NF-045','NF-050']),
t('NF-053','marketing','Build abandoned quiz and checkout recovery','P1','sales','2026-10-10','Create recovery paths for incomplete quiz and incomplete checkout.','Recovery messages trigger correctly without sending to converted customers.',['NF-046','NF-050']),
t('NF-054','marketing','Publish priority Knowledge Centre sales articles','P1','sales','2026-10-10','Publish strongest cost/price, problems, comparisons, reviews and buyer-question articles first.','Core objection-handling emails and sales conversations can link to useful published articles.'),
t('NF-055','marketing','Build launch landing pages and lead magnets','P1','sales','2026-10-10','Create campaign-specific pages and useful lead magnets such as programme finder and calculators.','Every launch acquisition campaign has a relevant destination and measurable conversion event.',['NF-046','NF-049']),
t('NF-056','marketing','Create launch creative pack','P1','sales','2026-10-11','Produce channel-ready creative using brand rules and real photography except Jeff/Steff.','Warm, organic and paid launch waves each have approved creative and copy.'),
t('NF-057','marketing','Build launch campaign schedule','P0','uat','2026-10-16','Schedule warm audience, organic/social and paid waves with owners, spend caps and stop conditions.','Launch calendar is approved and staged traffic can be controlled.',['NF-052','NF-056']),
t('NF-058','marketing','Create referral and review request flow','P2','beta','2026-10-24','Define post-success referral/review timing without interfering with launch-critical work.','Simple flow is ready or explicitly deferred.'),
t('NF-059','marketing','Rehearse launch communications','P0','freeze','2026-10-28','Test launch email, transactional email, SMS if used, support inbox and scheduled social links.','Every launch communication has correct links, sender, audience and fallback owner.',['NF-052','NF-057']),
t('NF-060','marketing','Verify analytics and commercial funnel reporting','P0','freeze','2026-10-29','Track visitors, leads, quiz starts/completions, checkout starts, purchases, AOV, subscriptions, CAC, activation and churn indicators.','A fresh test journey appears correctly in operational and commercial reporting.',['NF-048','NF-050'])
];
