import {t} from './seed-core.js';
export const tasks=[
// Programmes, Courses & Content
t('NF-021','content','Write programme specifications','P0','core','2026-09-23','For every launch programme define audience, outcome, duration, frequency, level, equipment, progression and safety boundaries.','Every launch programme has an approved specification used by content, site and app.',['NF-002']),
t('NF-022','content','Complete launch workout library','P0','core','2026-09-26','Build all workouts required by the launch programme catalogue, including warm-ups, cool-downs and alternatives.','No launch programme contains a missing workout or placeholder.',['NF-021']),
t('NF-023','content','Complete launch exercise library','P0','core','2026-09-27','For every launch exercise provide instructions, coaching cues, equipment, regression, progression and media.','Every exercise referenced by a launch workout resolves to complete content.',['NF-022']),
t('NF-024','content','Complete launch recipe catalogue','P0','sellable','2026-10-02','Load selected recipes with ingredients, method, portions, macros, allergens and believable real-food imagery.','Every launch recipe renders correctly with complete data and imagery.',['NF-014']),
t('NF-025','content','Build launch meal plans','P0','sellable','2026-10-03','Create meal plans supporting launch programmes and calorie/protein needs where applicable.','Each promoted plan is complete, nutritionally coherent and shoppable.',['NF-024','NF-007']),
t('NF-026','content','Complete launch courses','P1','sales','2026-10-09','Finish the small launch course set and remove anything not genuinely ready.','Every advertised course is complete, accessible and tied to a customer-journey purpose.',['NF-003']),
t('NF-027','content','Create onboarding education sequence','P0','sales','2026-10-09','Create Day 0, Day 1, Week 1–4 education covering NUFI, programme use, nutrition, consistency and progress.','Each onboarding step has final content, trigger and owner.',['NF-011','NF-021']),
t('NF-028','content','Run final content completeness audit','P0','freeze','2026-10-30','Audit programmes, workouts, exercises, recipes, meal plans, courses and imagery for missing or placeholder content.','No launch customer can reach placeholder, missing or draft content.',['NF-022','NF-023','NF-024','NF-025','NF-026']),
// Products & Supply Chain
t('NF-029','products','Approve suppliers and final product specifications','P0','core','2026-09-23','Confirm Raw Creations / relevant suppliers, formulas, samples, taste tests and specifications.','Every launch SKU has an approved supplier and signed-off specification.',['NF-004']),
t('NF-030','products','Create master SKU register','P0','core','2026-09-24','Create one SKU system used by supplier, stock, website, Stripe, fulfilment and accounts.','Every launch physical product has a unique SKU and naming convention.',['NF-004']),
t('NF-031','products','Confirm MOQ, unit cost and lead time by SKU','P0','core','2026-09-24','Record MOQ, unit cost, packaging cost, production time, delivery cost and reorder point.','Commercial and stock decisions can be made from one current supplier-cost table.',['NF-029','NF-030']),
t('NF-032','products','Complete packaging artwork and mandatory information','P0','sellable','2026-10-02','Finish pouches, tubs, boxes and labels including ingredients, allergens, nutrition, batch, best-before and storage fields.','Each launch SKU has print-ready packaging artwork pending/with compliance sign-off.',['NF-029','NF-030']),
t('NF-033','products','Approve product photography and pack shots','P1','sellable','2026-10-03','Create consistent real product pack shots aligned to Nutrition.Fitness visual rules.','Every product page has a credible, non-placeholder hero image and supporting imagery.',['NF-032']),
t('NF-034','products','Approve contribution margin by SKU and bundle','P0','sellable','2026-10-01','Calculate selling price less VAT, manufacture, packaging, fulfilment, postage support, Stripe, discount and acquisition allowance.','Contribution margin is known and approved for every launch SKU and bundle.',['NF-005','NF-031']),
t('NF-035','products','Place launch stock orders','P0','sellable','2026-10-04','Place orders early enough for production, packaging, delivery and contingency.','Purchase orders are acknowledged with delivery dates that protect launch.',['NF-031','NF-032','NF-034']),
t('NF-036','products','Finalise High Protein Kitchen print specification','P1','sales','2026-10-08','Approve final book, proof, printer, unit cost, MOQ, shipping weight and retail/bundle price.','Print-ready book and commercial specification are approved.'),
t('NF-037','products','Keep clothing range to launch-safe minimum','P2','beta','2026-10-23','Choose at most a minimal launch capsule if it does not distract from app, programmes or supplements.','Clothing is either explicitly deferred or limited to a small ready-to-fulfil range.'),
t('NF-038','products','Set stock controls and reorder rules','P0','freeze','2026-10-27','Define stock-on-hand, reserved stock, reorder points, backorder/out-of-stock rules and owner.','Inventory controls are live and tested before launch.',['NF-035'])
];
