import {t} from './seed-core.js';
export const tasks=[
// Offer & Commercial Model
t('NF-001','offer','Approve launch offer architecture','P0','lock','2026-09-18','Define the complete commercial ladder: NUFI, NUFI+, programmes, bolt-ons, meal planning, courses, supplements, books and bundles.','One signed-off offer map shows Product → Customer → Outcome → Included → Duration → Price → Recurring → Upgrade.'),
t('NF-002','offer','Lock launch programme catalogue','P0','lock','2026-09-18','Choose the base programmes and only the bolt-ons that will genuinely be ready for sale on 1 November.','Final launch programme list is approved with audience, goal, duration, level and inclusion rules.',['NF-001']),
t('NF-003','offer','Lock launch course catalogue','P0','lock','2026-09-19','Choose a deliberately small launch course set supporting acquisition, onboarding and retention.','Every launch course has a purpose, audience, owner and inclusion rule.',['NF-001']),
t('NF-004','offer','Lock launch supplement catalogue','P0','lock','2026-09-18','Choose exact supplement SKUs, pack sizes and flavours for launch.','Each launch supplement has final SKU, specification, supplier path, pack size and flavour.',['NF-001']),
t('NF-005','offer','Approve launch pricing and subscriptions','P0','lock','2026-09-20','Set one-off, monthly and annual pricing for app, programmes, supplements and bundles.','A single approved price book is the source of truth for site, Stripe, CRM and packaging.',['NF-001','NF-004']),
t('NF-006','offer','Approve bundle architecture','P0','lock','2026-09-20','Define simple bundles that make sense to a first-time buyer and preserve margin.','Each bundle has name, contents, saving, target buyer, contribution and next step.',['NF-002','NF-004','NF-005']),
t('NF-007','offer','Define meal-planning entitlement','P0','lock','2026-09-20','Decide whether meal planning is included in NUFI, NUFI+, programmes or a premium tier.','Entitlement rule is unambiguous and ready to implement across product, app and Stripe.',['NF-001']),
t('NF-008','offer','Define course entitlement','P1','lock','2026-09-20','Decide which courses are included with membership and which are sold or used for acquisition.','Course access matrix is approved.',['NF-003','NF-005']),
// NUFI Platform & Technology
t('NF-009','platform','Confirm production architecture and environments','P0','core','2026-09-22','Document production hosting, web app, mobile app, database, storage, email delivery, authentication, domains and monitoring.','Architecture diagram and environment list are approved with no ownership gaps.'),
t('NF-010','platform','Complete production authentication flows','P0','core','2026-09-23','Test registration, email verification, login, password reset, logout and account deletion.','All auth flows pass on production-like web, iOS and Android.',['NF-009']),
t('NF-011','platform','Complete onboarding, preferences and PAR-Q','P0','core','2026-09-24','Finish onboarding screens, goals, preferences, PAR-Q and consent steps.','A new user completes onboarding once, can edit allowed preferences and lands in the correct dashboard.',['NF-010']),
t('NF-012','platform','Complete programme entitlement and assignment logic','P0','core','2026-09-25','Connect purchases and assignments to the correct base programme and bolt-ons.','Test users receive only what they bought or were assigned.',['NF-002','NF-010']),
t('NF-013','platform','Complete workout and exercise delivery','P0','core','2026-09-25','Validate workout screens, exercise details, sets, reps, rest, alternatives and completion tracking.','A user can start, complete and revisit a workout without missing or broken content.',['NF-012']),
t('NF-014','platform','Complete recipe and meal-plan delivery','P0','core','2026-09-26','Validate recipes, meal plans, saved collections, shopping list and dietary filters.','A user can open a plan, save recipes and generate a coherent shopping list.',['NF-007']),
t('NF-015','platform','Complete progress, check-ins and notifications','P1','core','2026-09-27','Validate progress tracking, check-ins, reminders and notification preferences.','Core progress and reminder flows work and can be disabled by the user.',['NF-011']),
t('NF-016','platform','Prepare Apple App Store release assets','P0','sellable','2026-09-30','Prepare App Store listing copy, screenshots, privacy details, category and release notes.','App Store Connect record is complete and ready for submission.'),
t('NF-017','platform','Prepare Google Play release assets','P0','sellable','2026-09-30','Prepare Play Console listing copy, screenshots, data safety, category and release notes.','Play Console listing is complete and ready for submission.'),
t('NF-018','platform','Submit iOS and Android release candidates','P0','sales','2026-10-06','Submit both mobile release candidates early enough to allow rejection, repair and resubmission.','Both stores show submitted, in review or approved status with issues logged.',['NF-016','NF-017','NF-010','NF-011','NF-012','NF-013','NF-014']),
t('NF-019','platform','Set up error, uptime and performance monitoring','P0','sellable','2026-10-03','Add monitoring for login, APIs, critical customer actions and performance.','Named owner receives actionable alerts and launch dashboard can verify service health.',['NF-009']),
t('NF-020','platform','Complete device and browser test matrix','P0','uat','2026-10-15','Test current and older iPhone, current and older Android, tablet, desktop and mobile browsers.','Test matrix is signed off or every exception has an accepted workaround.',['NF-010','NF-011','NF-012','NF-013','NF-014'])
];
