import {t} from './seed-core.js';
export const tasks=[
// Business, Finance & Operations
t('NF-061','business','Confirm finance stack and reconciliation process','P0','core','2026-09-24','Confirm business accounts, QuickBooks, Stripe payout/reconciliation and finance ownership.','Weekly reconciliation process is documented and test transactions reconcile cleanly.'),
t('NF-062','business','Complete launch P&L and cash-flow forecast','P0','core','2026-09-25','Build base-case forecast including stock, packaging, app/site, people, ads, payment fees and fulfilment.','Cash requirement, break-even and monthly runway are visible through at least Q1 2027.',['NF-034']),
t('NF-063','business','Create organisation chart and responsibility matrix','P0','lock','2026-09-20','Name accountable owner, responsible person and backup for product, platform, content, support, marketing, fulfilment, finance and operations.','No launch-critical area is ownerless; each person knows their authority.'),
t('NF-064','business','Complete core website and subscription legal documents','P0','sales','2026-10-08','Prepare privacy, cookies, terms, subscription terms, refunds, returns, shipping and marketing consent wording.','Documents are reviewed, published and linked from checkout/account where required.'),
t('NF-065','business','Complete health and fitness safeguards','P0','sales','2026-10-08','Review PAR-Q, exercise disclaimers, medical limitations and AI coach boundaries.','Safeguards are consistent across app, web and onboarding.',['NF-011']),
t('NF-066','business','Complete supplement compliance review','P0','sellable','2026-10-02','Review ingredient, nutrition, allergen, claims, traceability, batch and label requirements before print.','Every launch label has documented compliance sign-off before production.',['NF-032']),
t('NF-067','business','Confirm insurance and supplier documentation','P0','sellable','2026-10-04','Confirm appropriate business/product cover and retain key supplier specifications and terms.','Required cover is active and critical supplier documents are stored centrally.',['NF-029']),
t('NF-068','business','Review grants and non-launch funding opportunities','P2','beta','2026-10-23','Keep useful funding research separate from launch blockers.','Opportunity list exists without consuming launch-critical delivery time.'),
// Launch Readiness & Support
t('NF-069','readiness','Define support model and escalation routes','P0','sales','2026-10-09','Set support email, hours, response target, refund authority and escalation for technical, order and health-related queries.','Every support category has an owner, backup and escalation path.',['NF-063']),
t('NF-070','readiness','Create top 30 support answers','P1','uat','2026-10-15','Write concise answers for likely app, programme, payment, supplement, shipping and account questions.','Support can answer the 30 highest-likelihood questions consistently.',['NF-069']),
t('NF-071','readiness','Run Sarah full-journey UAT scenario','P0','uat','2026-10-13','Run Facebook ad → site → quiz → recommendation → programme + protein → pay → account → NUFI → programme → emails → parcel.','Scenario completes end to end; every defect has owner, severity and fix date.',['NF-046','NF-048','NF-052','NF-043']),
t('NF-072','readiness','Run supplements-only UAT scenario','P0','uat','2026-10-14','Run a physical-products-only customer journey including subscription option, payment, confirmation, fulfilment and account.','Journey completes without creating unnecessary digital entitlements.',['NF-043','NF-044','NF-048']),
t('NF-073','readiness','Run NUFI annual-membership UAT scenario','P0','uat','2026-10-14','Run annual purchase, account creation, onboarding, access, renewal state and cancellation path.','Annual member gets correct entitlement and account controls.',['NF-043','NF-011']),
t('NF-074','readiness','Run failure-state UAT pack','P0','uat','2026-10-16','Test abandoned quiz, abandoned checkout, failed card, forgotten password, cancellation, refund and out-of-stock product.','Each failure state gives a clear customer message and recoverable operational path.',['NF-053','NF-069']),
t('NF-075','readiness','Recruit controlled real-world beta group','P0','beta','2026-10-19','Choose testers not involved in the build and give them real tasks rather than a guided demo.','Beta group covers key devices and customer types and has a structured feedback route.',['NF-071','NF-072','NF-073','NF-074']),
t('NF-076','readiness','Run real-world beta and triage findings','P0','beta','2026-10-23','Observe testers finding a programme, buying, onboarding, doing workouts, using meal plans, ordering products and contacting support.','Every finding is classified P0/P1/P2; launch blockers are fixed or explicitly no-go.',['NF-075']),
t('NF-077','readiness','Freeze major feature development','P0','freeze','2026-10-26','After freeze, accept only launch blockers, broken journeys, incorrect data, compliance, tracking and severe usability defects.','Change log shows no discretionary scope added after freeze.',['NF-076']),
t('NF-078','readiness','Run fulfilment and stock rehearsal','P0','freeze','2026-10-27','Place internal test orders, pick, pack, label, dispatch and track them.','Physical order rehearsal passes and stock count reconciles.',['NF-038','NF-044']),
t('NF-079','readiness','Run final communications rehearsal','P0','freeze','2026-10-28','Test launch and transactional communications from real triggers.','Every message reaches the right audience with correct links and fallback owner.',['NF-059']),
t('NF-080','readiness','Run final analytics and monitoring rehearsal','P0','freeze','2026-10-29','Verify events, dashboards, uptime alerts, error reporting and payment visibility with fresh test journeys.','Test journey appears correctly in operational and commercial reporting.',['NF-019','NF-060']),
t('NF-081','readiness','Complete final stock and content audit','P0','freeze','2026-10-30','Confirm stock on hand, website availability, app content, prices and published terms all match the launch plan.','No mismatch exists between advertised, purchasable and deliverable.',['NF-028','NF-035','NF-043','NF-064']),
t('NF-082','readiness','Run 31 October GO / NO-GO checklist','P0','gonogo','2026-10-31','Review technology, products, content, customer journey, commercial settings, compliance, support and fulfilment.','Every P0 is Done/Approved or an accountable decision explicitly accepts the risk.',['NF-077','NF-078','NF-079','NF-080','NF-081']),
t('NF-083','readiness','Launch Wave 1 to warm audience','P0','launch','2026-11-01','Open first to the warm list and monitor payments, errors, fulfilment, support volume and activation before expanding traffic.','Wave 1 metrics are within agreed limits with no unresolved launch blocker.',['NF-082']),
t('NF-084','readiness','Release Waves 2 and 3 when thresholds pass','P0','launch','2026-11-01','Expand to organic/social, then paid acquisition only after Wave 1 health checks pass.','Traffic expansion is a deliberate go decision based on live conversion and operational health.',['NF-083'])
];
