import {state,workstreams,phases,save,now,esc,ws,ph,statusLabel,taskById,ownerNames,dueClass,formatDate,addActivity,newTaskId} from './store.js';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];

export function openTask(id,refresh){const t=taskById(id);if(!t)return;$('#dialog-task-id').textContent=t.id;$('#dialog-task-title').textContent=t.title;const deps=(t.deps||[]).map(taskById).filter(Boolean);$('#dialog-body').innerHTML=`
<section class="dialog-section"><div class="task-meta"><div class="meta-box"><small>Priority</small><strong><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span></strong></div><div class="meta-box"><small>Workstream</small><strong>${esc(ws(t.workstream)?.name)}</strong></div><div class="meta-box"><small>Phase</small><strong>${esc(ph(t.phase)?.name)}</strong></div><div class="meta-box"><small>Due</small><strong class="${dueClass(t)}">${formatDate(t.due)}</strong></div></div></section>
<section class="dialog-section"><h3>Instructions</h3><p>${esc(t.instructions)}</p></section><section class="dialog-section"><h3>Done means</h3><p>${esc(t.done)}</p></section>
<section class="dialog-section"><h3>Dependencies</h3>${deps.length?deps.map(d=>`<button class="link-button" data-dep="${d.id}">${d.id} · ${esc(d.title)}</button>`).join('<br>'):'<p>None.</p>'}</section>
<section class="dialog-section"><h3>Assignment & status</h3><div class="task-edit"><label><span>Owner<select id="edit-owner">${ownerNames().map(n=>`<option ${n===t.owner?'selected':''}>${esc(n)}</option>`).join('')}</select></span></label><label><span>Status<select id="edit-status">${['todo','in_progress','waiting','submitted','changes','approved','done'].map(s=>`<option value="${s}" ${s===t.status?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></span></label></div></section>
<section class="dialog-section"><h3>Submit work</h3><div class="task-edit"><label class="wide"><span>Repository / Drive / Canva / document URL<input id="submission-url" type="url" placeholder="https://..."></span></label><label class="wide"><span>Submission note<textarea id="submission-note" rows="3" placeholder="What has been completed? What should the reviewer check?"></textarea></span></label></div><div class="dialog-actions" style="padding:12px 0 0"><button class="primary" id="submit-work">Submit for approval</button></div>${(t.submissions||[]).map(s=>`<div class="submission"><a href="${esc(s.url)}" target="_blank" rel="noreferrer">Open submitted work ↗</a><p>${esc(s.note)}</p><small>${esc(s.by)} · ${new Date(s.at).toLocaleString('en-GB')}</small></div>`).join('')}</section>
<section class="dialog-section"><h3>Review</h3><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="success" id="approve-task">Approve</button><button class="danger" id="changes-task">Request changes</button><button class="ghost" id="mark-done">Mark done</button></div></section>
<section class="dialog-section"><h3>Notes</h3><div class="task-edit"><label class="wide"><span>Add note<textarea id="task-note" rows="2"></textarea></span></label></div><div class="dialog-actions" style="padding:10px 0 0"><button class="ghost" id="add-note">Add note</button></div>${(t.notes||[]).map(n=>`<div class="submission"><p>${esc(n.text)}</p><small>${esc(n.by)} · ${new Date(n.at).toLocaleString('en-GB')}</small></div>`).join('')}</section>
<section class="dialog-section"><h3>Activity</h3><div class="activity">${(t.activity||[]).map(a=>`<div><strong>${esc(a.by)}</strong> · ${new Date(a.at).toLocaleString('en-GB')}<br>${esc(a.text)}</div>`).join('')}</div></section>`;
$('#edit-owner').addEventListener('change',e=>{t.owner=e.target.value;addActivity(t,`Owner changed to ${t.owner}.`);save();refresh()});
$('#edit-status').addEventListener('change',e=>{t.status=e.target.value;addActivity(t,`Status changed to ${statusLabel(t.status)}.`);save();refresh()});
$('#submit-work').addEventListener('click',()=>{const url=$('#submission-url').value.trim(),note=$('#submission-note').value.trim();if(!url){alert('Add a link to the submitted work.');return}t.submissions=t.submissions||[];t.submissions.unshift({url,note,by:t.owner==='Unassigned'?'Team':t.owner,at:now()});t.status='submitted';addActivity(t,'Work submitted for approval.',t.owner==='Unassigned'?'Team':t.owner);save();openTask(t.id,refresh);refresh()});
$('#approve-task').addEventListener('click',()=>{t.status='approved';addActivity(t,'Work approved.');save();openTask(t.id,refresh);refresh()});
$('#changes-task').addEventListener('click',()=>{const reason=prompt('What needs changing?')||'Changes requested.';t.status='changes';t.notes=t.notes||[];t.notes.unshift({text:reason,by:'James',at:now()});addActivity(t,'Changes requested: '+reason);save();openTask(t.id,refresh);refresh()});
$('#mark-done').addEventListener('click',()=>{t.status='done';addActivity(t,'Task marked done.');save();openTask(t.id,refresh);refresh()});
$('#add-note').addEventListener('click',()=>{const text=$('#task-note').value.trim();if(!text)return;t.notes=t.notes||[];t.notes.unshift({text,by:'James',at:now()});addActivity(t,'Note added.');save();openTask(t.id,refresh)});
$$('[data-dep]').forEach(b=>b.addEventListener('click',()=>openTask(b.dataset.dep,refresh)));$('#task-dialog').showModal()}

export function wireNewTask(refresh,setView){$('#new-task-btn').addEventListener('click',()=>{const w=$('#new-workstream'),p=$('#new-phase'),o=$('#new-owner');w.innerHTML=workstreams.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');p.innerHTML=phases.map(x=>`<option value="${x.id}">${x.name} · ${x.dates}</option>`).join('');o.innerHTML=ownerNames().map(n=>`<option>${esc(n)}</option>`).join('');$('#new-task-dialog').showModal()});$$('[data-close-new]').forEach(b=>b.addEventListener('click',()=>$('#new-task-dialog').close()));$('#new-task-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=newTaskId();state.tasks.push({id,workstream:fd.get('workstream'),title:fd.get('title'),priority:fd.get('priority'),phase:fd.get('phase'),due:fd.get('due'),instructions:fd.get('instructions'),done:fd.get('done'),deps:[],owner:fd.get('owner'),status:'todo',notes:[],submissions:[],activity:[{at:now(),by:'James',text:'Task created.'}]});save();e.currentTarget.reset();$('#new-task-dialog').close();setView('tasks')})}
