/** Server-only platform access. Tokens never enter browser storage or JSON responses. */
import {timingSafeEqual} from 'node:crypto';
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export function reply(res,status,data){res.setHeader('Cache-Control','no-store, private');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Vary','Cookie');return res.status(status).json(data);}
export function fail(res,error){return reply(res,error.status||503,{error:error.status?error.message:'The service could not confirm this request. Your existing data has not been replaced.'});}
export function origins(env){const values=[env.SITE_URL,...(env.NUFI_ALLOWED_ORIGINS||'').split(',')].filter(Boolean);if(!values.length)throw new HttpError(503,'The website connection has not been configured.');return values.map(v=>{const u=new URL(v);if(u.protocol!=='https:'&&!(env.NODE_ENV==='test'&&u.hostname==='localhost'))throw new HttpError(503,'The website origin needs HTTPS.');return u.origin;});}
export function body(req,env,max=2000000){if(!origins(env).includes(req.headers.origin))throw new HttpError(403,'Please make this change from the Nutrition.Fitness website.');if(!/^application\/json(?:;|$)/i.test(req.headers['content-type']||''))throw new HttpError(415,'Use the website form to submit this change.');let b;try{const s=typeof req.body==='string'?req.body:JSON.stringify(req.body);if(!s||Buffer.byteLength(s)>max)throw new Error();b=JSON.parse(s);}catch{throw new HttpError(400,'The request could not be read or was too large.');}if(!b||typeof b!=='object'||Array.isArray(b))throw new HttpError(400,'Check the request format.');return b;}
export const email=v=>{if(typeof v!=='string'||v.length>254||!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(v.trim()))throw new HttpError(400,'Enter a valid email address.');return v.trim().toLowerCase();};
export function text(v,label,max=100){if(typeof v!=='string'||!v.trim()||v.length>max||/[<>\x00-\x1f]/.test(v))throw new HttpError(400,`Check ${label}.`);return v.trim();}
export const uuid=v=>{if(typeof v!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v))throw new HttpError(400,'A valid request identifier is required.');return v;};
export function platformConfigured(env){try{return !!(env.SUPABASE_URL&&new URL(env.SUPABASE_URL).protocol==='https:'&&env.SUPABASE_ANON_KEY&&env.SUPABASE_SERVICE_ROLE_KEY&&env.SITE_URL);}catch{return false;}}
export function platform(env,fetcher=fetch){if(!platformConfigured(env))throw new HttpError(503,'Account storage is not connected in this deployment. Your browser plan is still available.');const base=env.SUPABASE_URL.replace(/\/$/,'');return async(endpoint,{method='GET',payload,access,service=false,headers={}}={})=>{const key=service?env.SUPABASE_SERVICE_ROLE_KEY:env.SUPABASE_ANON_KEY;const response=await fetcher(base+endpoint,{method,headers:{apikey:key,Authorization:`Bearer ${access||key}`,'Content-Type':'application/json',...headers},body:payload===undefined?undefined:JSON.stringify(payload),signal:AbortSignal.timeout(10000)});const data=await response.json().catch(()=>null);if(!response.ok){const error=new HttpError(response.status===401?401:response.status===409||data?.code==='40001'?409:503,response.status===401?'Please sign in again.':response.status===409||data?.code==='40001'?'A newer copy has been saved. Reload the account copy before editing.':'The account service did not confirm this change. Please try again.');error.upstreamCode=data?.code;throw error;}return data;};}
export function cookies(req){const values={};for(const part of (req.headers.cookie||'').split(';')){const p=part.trim().indexOf('=');if(p<1)continue;const k=part.trim().slice(0,p);try{values[k]=decodeURIComponent(part.trim().slice(p+1));}catch{}}return values;}
const ACCESS='__Host-nufi-access',REFRESH='__Host-nufi-refresh';
export function setSession(res,session){if(typeof session.access_token!=='string'||typeof session.refresh_token!=='string'||session.access_token.length>6000)throw new HttpError(503,'Sign-in did not return a valid session.');res.setHeader('Set-Cookie',[`${ACCESS}=${encodeURIComponent(session.access_token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.min(session.expires_in||3600,3600)}`,`${REFRESH}=${encodeURIComponent(session.refresh_token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`]);}
export function clearSession(res){res.setHeader('Set-Cookie',[ACCESS,REFRESH].map(k=>`${k}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`));}
export async function session(req,res,env,fetcher=fetch){const c=cookies(req),api=platform(env,fetcher);let token=c[ACCESS];if(token){try{const user=await api('/auth/v1/user',{access:token});if(!user?.id||!user.email_confirmed_at)throw new HttpError(401,'Verify your email before using this account.');return {user,access:token,api};}catch(e){if(e.status!==401)throw e;}}
 if(c[REFRESH]){try{const next=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',payload:{refresh_token:c[REFRESH]}});const user=await api('/auth/v1/user',{access:next.access_token});if(!user?.id||!user.email_confirmed_at)throw new HttpError(401,'Verify your email first.');setSession(res,next);return {user,access:next.access_token,api};}catch{clearSession(res);throw new HttpError(401,'Your session ended. Sign in again; your local account copy has not been deleted.');}}
 throw new HttpError(401,'Sign in to use your account copy.');}
export async function verifyBot(token,action,env,fetcher=fetch){if(!env.TURNSTILE_SECRET_KEY||!env.TURNSTILE_SITE_KEY)throw new HttpError(503,'Signup verification is not connected yet.');if(typeof token!=='string'||!token||token.length>2048)throw new HttpError(400,'Complete the security check and try again.');const res=await fetcher('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:env.TURNSTILE_SECRET_KEY,response:token}),signal:AbortSignal.timeout(7000)});const data=await res.json();if(!res.ok||data.success!==true||data.action!==action||!origins(env).some(o=>new URL(o).hostname===data.hostname))throw new HttpError(400,'The security check expired or failed. Refresh it and try again.');}
export function isAdmin(user,env){return (env.NUFI_ADMIN_USER_IDS||'').split(',').map(v=>v.trim()).includes(user.id);}
export function requireSecret(req,value){const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!value||!token||Buffer.byteLength(token)!==Buffer.byteLength(value)||!timingSafeEqual(Buffer.from(token),Buffer.from(value)))throw new HttpError(401,'Not authorised.');}
