/** The catalogue is for design review. All prices, sizes, formulations and curricula
 *  must be signed off before sales are enabled. Prices are integer GBP pence. */
import {collectionProducts} from './collection-books.mjs';
export const site = {
  name: 'nutrition.fitness', currency: 'GBP', preview: true,
  shipping: { fee: 395, freeOver: 5000 }, subscriptionDiscount: 10,
  links: { app: '', login: '', support: '', customerPortal: '' },
  strapline: 'Real food. Real progress. A fitter, happier you.'
};
export const products = [
  { id:'plain-whey', name:'Plain whey protein', short:'Plain whey.', category:'powders', price:2900, size:'1 kg', type:'physical', recurring:true, color:'cream', art:'pouch', label:'whey\nprotein.', quip:'Plain on purpose. You bring the flavour.', description:'One neutral base. A different flavour when you fancy it. Keep your protein simple and choose a flavour shot separately.', details:['Unflavoured base, designed for the separate flavour-shot system.','Choose one-off purchase or a regular delivery.','No shot is included unless you add one.'], caution:'Proposed whey product. Contains milk. Full ingredients, nutrition, serving instructions and other allergen information must be confirmed from the final supplier specification.' },
  { id:'plant-protein', name:'Plain plant protein', short:'Plain plant.', category:'powders', price:3200, size:'1 kg', type:'physical', recurring:true, color:'sage', art:'pouch', label:'plant\nprotein.', quip:'The plant-based one. Still not a houseplant.', description:'A plain plant-protein option for your cupboard, with flavour kept in a separate bottle. Pick the base that suits you. Then make it your own.', details:['An unflavoured plant-protein option.','Flavour shots are separate, so you choose the combination.','Final blend and supplier details are being confirmed.'], caution:'Proposed product. Plant-based does not mean allergen-free. Final ingredients, allergens, nutrition and suitability need supplier confirmation.' },
  { id:'creatine', name:'Plain creatine powder', short:'Plain creatine.', category:'powders', price:1600, size:'250 g', type:'physical', recurring:true, color:'aqua', art:'pouch', label:'creatine\npowder.', quip:'No dramatic name. Just the powder.', description:'A straightforward, unflavoured addition to the range. No superhero branding. No thirty-seven-word performance promises.', details:['A separate product, not an ingredient silently added to your protein.','Buy once or choose a delivery interval that suits your usage.','Always follow the final label directions.'], caution:'Concept product. Composition, serving directions, age restrictions, suitability and label information require approval before sale. No dosage is prescribed in this preview.' },
  ...[
    ['vanilla','Vanilla','cream','A classic. Without the commitment.'],
    ['chocolate','Chocolate','plum','For the days that clearly require chocolate.'],
    ['salted-caramel','Salted caramel','peach','A little sweet. A little salty. Relatable.'],
    ['strawberry','Strawberry','blush','Your protein has a fruity side.'],
    ['banana','Banana','sage','Going bananas. In a very organised way.'],
    ['hazelnut','Hazelnut','aqua','Another flavour. Not another kilo of powder.']
  ].map(([slug,name,color,quip])=>({id:`shot-${slug}`,name:`${name} flavour shot`,short:name,category:'shots',price:695,size:'30 ml · concept size',type:'physical',recurring:true,color,art:'bottle',label:name.toLowerCase(),quip,description:`Add ${name.toLowerCase()} flavour separately to your plain protein. Keep the powder. Change your mind about the flavour. That is allowed.`,details:['Pipette-style flavour shot, not a ready-to-drink shake.','Sold separately from the protein powder.','Choose one flavour or mix a selection in your box.'],caution:'Proposed flavour and pack size. Ingredients, allergens, sweeteners, serving instructions and compatibility must be verified before sale. A flavour name does not establish whether an allergen is present.'})),
  {id:'high-protein-kitchen',category:'books',type:'digital',recurring:false,color:'sage',label:'High Protein Kitchen'},
  ...collectionProducts,
  {id:'nufi-membership',name:'NUFI+ membership',short:'NUFI+',category:'membership',price:1499,annualPrice:9900,type:'digital',recurring:true,color:'aqua',art:'membership',label:'NUFI+',quip:'Less figuring out. More getting on with it.',description:'Programmes, meal planning, shopping lists, courses and progress. The useful bits, brought together.',caution:'Example pricing for review. No membership or real account is activated in this preview.'}
];
const kitchen = products.find(p=>p.id==='high-protein-kitchen');
Object.assign(kitchen, {
  name:'The High Protein Kitchen', short:'The High Protein Kitchen',
  price:null, priceStatus:'awaiting-approval', availability:'coming-soon',
  size:'100 recipes · 143-page digital edition', art:'published-book',
  image:'/assets/cookbook/high-protein-kitchen-cover.webp',
  formats:['Digital PDF','Hardback'],
  quip:'Proper food. A little less fuss.',
  description:'100 recipes for real life: breakfasts, lunches, dinners, snacks and drinks. The complete High Protein Kitchen, with the original recipe photographs, clear methods and the supplied nutrition figures.',
  details:['22 breakfasts, 24 lunches, 25 dinners, 14 snacks and 15 smoothies and drinks.','143 pages in the supplied digital edition, including the practical kitchen, nutrition and fitness notes.','The salmon, coriander & lime rice bowl on the cover is recipe 67, page 99.','Explore all 100 recipes on the website and save your favourites to your meal planner.'],
  caution:'Launching 1 November 2026 at 9am UK time. Digital and hardback pricing, physical availability and delivery terms are still to be confirmed. No payment is taken and no paid PDF download is exposed on this page.'
});
export const programmes = [
  {slug:'start',name:'Start',title:'A start you can actually stick to.',tag:'Start here',level:'Beginner',place:'Home or gym',weeks:6,sessions:3,minutes:'20–30',color:'aqua',icon:'dumbbell',description:'For anyone who would like to get going without being told to become a different person by Thursday.',goal:'Build a routine',outcome:'Find your feet, learn the movements and build a week you can repeat.',focus:['Simple full-body sessions','A gradual introduction to training','Food planning that fits your week'],quip:'No previous enthusiasm required.'},
  {slug:'lose',name:'Lose',title:'Less all-or-nothing. More getting somewhere.',tag:'Feel better in yourself',level:'All levels',place:'Home or gym',weeks:12,sessions:3,minutes:'25–40',color:'blush',icon:'heart',description:'A proposed fat-loss programme built around consistency, realistic training and food you still look forward to.',goal:'Manage weight',outcome:'Work towards your goals without turning every meal into a maths exam.',focus:['A manageable weekly structure','Personal nutrition targets from onboarding','Progress reviews beyond the scales'],quip:'Cake has not been appointed the enemy.'},
  {slug:'build',name:'Build',title:'Build strength. Keep a social life.',tag:'Get stronger',level:'Intermediate',place:'Gym',weeks:12,sessions:4,minutes:'35–50',color:'sage',icon:'dumbbell',description:'A clear training structure for people who want to build muscle without collecting seventeen contradictory routines.',goal:'Build muscle',outcome:'Know what you are working on, what you did last time and what comes next.',focus:['Structured gym sessions','Training progress in one place','Protein-forward meal planning'],quip:'The spreadsheet can stay at work.'},
  {slug:'strong',name:'Strong',title:'Strong enough for the everyday stuff.',tag:'Everyday strength',level:'All levels',place:'Gym',weeks:8,sessions:3,minutes:'30–45',color:'peach',icon:'dumbbell',description:'Training with a purpose beyond looking busy near a squat rack.',goal:'Get stronger',outcome:'Build a more capable you, one sensible training week at a time.',focus:['Core movement patterns','A repeatable strength routine','Space to review and adjust'],quip:'Shopping bags are not going to carry themselves.'},
  {slug:'fit',name:'Fit',title:'More energy for the rest of your life.',tag:'Feel fitter',level:'All levels',place:'Home or gym',weeks:8,sessions:3,minutes:'20–35',color:'aqua',icon:'heart',description:'A balanced mix of strength and conditioning. Nothing here requires fitness to become your hobby.',goal:'Feel fitter',outcome:'Make movement part of your week, rather than another thing on your guilt list.',focus:['Strength and conditioning','Sessions for busy weeks','Recovery kept in the plan'],quip:'The stairs are not a personality test.'},
  {slug:'home',name:'Home',title:'Your living room. A surprisingly good start.',tag:'Train at home',level:'Beginner',place:'Home',weeks:6,sessions:3,minutes:'20–30',color:'sage',icon:'house',description:'An at-home programme for people who would rather skip the commute than skip the workout.',goal:'Train at home',outcome:'Make training easier to start, with a setup that fits your space.',focus:['Home-friendly movement options','Equipment preferences from onboarding','A routine around your schedule'],quip:'Pyjamas are between you and your curtains.'},
  {slug:'run',name:'Run',title:'One foot. Then the other. A bit of a plan helps.',tag:'Get outdoors',level:'Beginner',place:'Outdoors',weeks:8,sessions:3,minutes:'20–40',color:'blush',icon:'run',description:'A proposed running pathway with room to build gradually and keep strength work in the picture.',goal:'Start running',outcome:'Find a running routine you feel ready to return to.',focus:['A gradual running structure','Supporting strength sessions','Rest days that mean rest days'],quip:'No motivational shouting required.'},
  {slug:'hybrid',name:'Hybrid',title:'A bit of both. A lot less guessing.',tag:'Mix it up',level:'Intermediate',place:'Gym and outdoors',weeks:8,sessions:4,minutes:'30–50',color:'peach',icon:'bolt',description:'Strength and conditioning in one proposed programme, instead of two plans fighting over your calendar.',goal:'Train for more',outcome:'Bring your different training goals into a single, manageable week.',focus:['Strength and conditioning together','A clear weekly rhythm','Progress and recovery reviews'],quip:'Because doing everything at once is not a plan.'}
];
export const courses = [
  {slug:'nutrition-foundations',name:'Nutrition, without the nonsense',short:'Nutrition foundations',category:'Nutrition',color:'sage',icon:'cutlery',tag:'Start with the useful stuff',intro:'Understand your food without needing a second degree. Or a ring light.',modules:[['Start with your actual life','Look at your routine before deciding what needs to change.'],['A plate that makes sense','Get to know the different parts of a meal.'],['Protein, in plain English','Understand where protein fits into everyday eating.'],['Planning without the perfection','Create a practical approach to meals and shopping.'],['Put it into practice','Build a simple week inside NUFI+.']],quote:'Your dinner does not need a mission statement.'},
  {slug:'habits-that-stick',name:'Habits for actual humans',short:'Habits that stick',category:'Habits',color:'blush',icon:'repeat',tag:'For the Monday starters',intro:'A practical course about getting back to it. Including the weeks that go a bit sideways.',modules:[['Pick one thing','Decide what would make your days a little easier.'],['Make the first step smaller','Reduce the effort it takes to begin.'],['Build it into your day','Find a repeatable place for your new routine.'],['Plan for the awkward bits','Think through busy days and changes of plan.'],['Carry on, not start again','Review what happened without the guilt trip.']],quote:'Monday has had quite enough responsibility.'},
  {slug:'meal-planning',name:'Dinner. Without the daily debate.',short:'Meal planning made simple',category:'Food',color:'aqua',icon:'cart',tag:'Take the faff out of food',intro:'Learn to put a useful meal plan together, shop for it and actually eat the things you bought.',modules:[['What does your week look like?','Plan for time, preferences and the people you eat with.'],['Choose a handful of reliable meals','Build a short list worth repeating.'],['Turn the plan into a shopping list','Work out what you need and what is already in the cupboard.'],['Make tomorrow a little easier','Prepare the useful bits in advance.'],['Leave room for real life','Swap meals without throwing away the whole plan.']],quote:'A fridge full of good intentions is still not dinner.'},
  {slug:'sleep-and-recovery',name:'Rest. It is in the plan.',short:'Sleep & recovery',category:'Recovery',color:'peach',icon:'moon',tag:'You are not a rechargeable drill',intro:'An introduction to making space for rest and a calmer evening routine. Educational content, not treatment for sleep problems.',modules:[['Notice your current routine','Look at your evenings and recovery habits.'],['Make room for winding down','Explore practical changes to your surroundings and schedule.'],['Keep rest in the week','Understand the role of non-training days.'],['Review what works for you','Build a routine without turning sleep into another competition.']],quote:'Your sofa has been training for this.'},
  {slug:'confidence-in-the-gym',name:'Less wandering. More working out.',short:'Gym confidence',category:'Training',color:'sage',icon:'dumbbell',tag:'Know your way around',intro:'Get familiar with a gym session before you find yourself pretending to understand a complicated machine.',modules:[['Read your plan','Understand the layout of a workout.'],['Get to know the space','Make a simple first-visit checklist.'],['Ask, adjust, practise','Know when to ask a qualified instructor for help.'],['Track the useful bits','Record enough to know where to pick up next time.']],quote:'Nobody is born knowing what that machine does.'}
];
export const recipes = [
 {slug:'chicken-rice-bowl',name:'The anything-but-boring chicken bowl',category:'Lunch',time:25,image:'chicken-bowl',color:'sage',intro:'A useful lunch, with considerably more personality than plain chicken in a plastic box.',ingredients:['Chicken breast','Rice or your preferred grain','Cucumber and avocado','Mixed leaves','A dressing you enjoy'],note:'Lunch sorted. Meeting enthusiasm sold separately.'},
 {slug:'berry-breakfast',name:'The blender-has-a-job smoothie',category:'Breakfast',time:5,image:'food-breakfast',color:'blush',intro:'Berries, a protein base and a blender. A fairly achievable morning ambition.',ingredients:['Milk or a suitable alternative','Your approved plain protein','Mixed berries','Banana','Optional flavour shot, following its label'],note:'Put the lid on. We believe in you.'},
 {slug:'friday-fakeaway',name:'The staying-in burger',category:'Dinner',time:30,image:'food-fakeaway',color:'peach',intro:'A fakeaway concept for the nights when cooking needs a more convincing argument.',ingredients:['Your preferred burger patty','Burger bun','Potatoes for wedges','Tomato and lettuce','A sauce you like'],note:'No delivery fee. There is washing-up, though.'},
 {slug:'snack-box',name:'The four-o’clock rescue box',category:'Snacks',time:10,image:'food-snacks',color:'aqua',intro:'A little preparation for the time of day when your brain starts negotiating with the biscuit tin.',ingredients:['Yoghurt or a suitable alternative','Fresh fruit','A small selection of nuts, where suitable','Your preferred savoury option'],note:'Future-you sends their regards.'},
 {slug:'grain-bowl',name:'The use-what-you-have bowl',category:'Lunch',time:20,image:'food-salmon',color:'sage',intro:'A mix-and-match meal idea, not an instruction to buy fourteen things you will only use once.',ingredients:['A cooked grain','Your preferred protein source','Vegetables you enjoy','Herbs and dressing'],note:'Your fridge would like a word.'},
 {slug:'breakfast-jar',name:'The night-before breakfast',category:'Breakfast',time:10,image:'food-snacks',color:'blush',intro:'A breakfast idea for mornings that do not leave a lot of room for improvisation.',ingredients:['Yoghurt or a suitable alternative','Oats','Berries','Optional seeds or nuts, where suitable'],note:'One less decision before coffee.'}
];
export const journal = [
 {slug:'why-we-built-nufi',category:'Our story',title:'For people who want the result. Not another hobby.',intro:'We started with a simple question: why is looking after yourself so much work before you have even done the workout?',paragraphs:['Nutrition.Fitness began with the wish for something simpler. A plan that joined up training, food, shopping and the rest of real life. Not another pile of information to organise yourself.','NUFI+ is the system we are building around that idea. Jeff and Steff give it a voice. The programmes and meal planning give it something useful to say.','We take what we are building seriously. We just do not think every sentence about a workout needs to sound like an army briefing.'],image:'more-good-days'},
 {slug:'plain-protein-different-flavour',category:'Behind the products',title:'Plain protein. Anything-but-plain plans.',intro:'Buying a kilo of one flavour is quite a commitment to a mood you were in on a Tuesday.',paragraphs:['Our product direction is simple: keep the protein neutral and put the flavour in a separate shot. You can keep using the same base without keeping the same flavour.','That means the shop needs to be clear about what is in your basket. A plain powder is one item. A flavour shot is another. A bundle shows you both. Nothing sneaks in wearing a discount badge.','The launch range, formulations and final prices still need sign-off. The idea, however, is settled: less cupboard clutter, more choice.'],image:'chicken-bowl'},
 {slug:'a-plan-for-tuesday',category:'Real life',title:'Your plan should know about Tuesdays.',intro:'The imaginary version of you has endless time. The actual version has a calendar.',paragraphs:['A useful plan starts with the life you have. The hours you work. The people you feed. The days when getting out of the door is already an achievement.','That is why NUFI starts by asking about your preferences and schedule. The plan is there to help you decide what comes next, not add another impossible list.','Missed something? Review it. Adjust it. Carry on. Monday does not need to be involved.'],image:'more-good-days'}
];
