/** Catalogue descriptions share the same bases as the programme finder. */
import {BASES} from '../public/programme-finder.mjs';
const facts={
 core:{image:'knowledge-41',courseImage:'knowledge-42',eyebrow:'Your foundation',quote:'The basics. Done well. Repeated often.',learn:'Learn your movements, make space in your week and record a useful starting point.',structure:['Balanced movement, rather than an arms-only plan.','Strength, movement and general conditioning remain the foundation.','Your focus add-ons change the emphasis—not the existence of the rest of your body.'],course:['Set a realistic starting point','Keep the foundation underneath your focus','Make your first week repeatable']},
 build:{image:'programme-build',courseImage:'knowledge-32',eyebrow:'Muscle-building',quote:'More muscle. Less making it up.',learn:'Understand your training record, your chosen focus and how the plan fits alongside food and recovery.',structure:['Resistance training with a muscle-building purpose.','core.arms and build.arms are different: the base changes the role of the extra work.','Your available time and equipment are settled before training volume is added.'],course:['Choose a muscle-building base','Use a training record that makes sense','Fit focus work around the complete programme']},
 lean:{image:'knowledge-22',courseImage:'knowledge-21',eyebrow:'A sustainable approach',quote:'A plan for real life. Not life on hold.',learn:'Connect a realistic training routine to your meal planning and review the week without an all-or-nothing reset.',structure:['Training and food planning work together.','No promise of reducing fat from one body part.','Your nutrition targets come from onboarding—not the name of this programme.'],course:['Make the plan fit your week','Plan food without guessing your targets','Review, adjust and carry on']},
 fit:{image:'knowledge-2',courseImage:'knowledge-24',eyebrow:'General fitness',quote:'For more “let’s go”. Less “give me a minute”.',learn:'Choose a repeatable conditioning routine, make room for strength and build a useful habit of recording sessions.',structure:['General conditioning and everyday fitness.','Strength and mobility can support the base.','Choose run, swim or bike when your main goal belongs to that specific sport.'],course:['Decide what fitter means to you','Choose a week you can actually repeat','Keep strength and recovery in the picture']},
 run:{image:'knowledge-1',courseImage:'knowledge-34',eyebrow:'A running-led plan',quote:'One foot. Then the other. With a bit of a plan.',learn:'Prepare your running routine, supporting sessions and a sensible record of where you are starting.',structure:['Running remains the main activity.','Supporting strength and mobility fit around it.','Your starting point and full screening set your plan—not an assumed pace or distance.'],course:['Start from the running you do now','Arrange your week before chasing a number','Record the useful bits']},
 swim:{image:'programme-swim',courseImage:'knowledge-18',eyebrow:'A swimming-led plan',quote:'Less lane-envy. More knowing what’s next.',learn:'Check your pool access, record your current swimming confidence and understand where support fits.',structure:['A dedicated swimming base—not fit with a different picture.','Pool access and water confidence are essential onboarding details.','Technique support is separate from simply adding more lengths.'],course:['Get the practical details right','Describe your actual starting point','Put support and recovery into the week']},
 bike:{image:'programme-bike',courseImage:'knowledge-4',eyebrow:'A cycling-led plan',quote:'A little structure. A little more momentum.',learn:'Match your plan to your indoor or outdoor setup and build a useful picture of your weekly availability.',structure:['Cycling is the main activity.','Indoor and outdoor access are recorded explicitly.','Supporting strength, mobility and endurance are fitted to your week.'],course:['Match the plan to your bike setup','Make room in your real calendar','Track what helps you come back']}
};
export const SYSTEM = Object.values(BASES).map(b=>({...b,...facts[b.name]}));
export const LESSONS = SYSTEM.flatMap(b=>b.course.map((title,i)=>({id:`${b.name}-${i+1}`,base:b.name,index:i,title,
 paragraphs:i===0?[
  b.summary,
  `Your ${b.name} programme starts with the person you are now: your experience, the equipment you can use and the time you can realistically make. The programme finder is a recommendation, not a prescription. Full onboarding is where the details belong.`,
  'Write down what a useful first month would look like. Choose something you can recognise in real life: completing the sessions you planned, understanding your next step, or having dinner organised before you are hungry. A larger outcome can remain the goal without being your only measure of progress.'
 ]:i===1?[
  b.structure[1],
  'Select a base first. Add a focus because it matters to you, not because every checkbox is available. You can choose more than one focus; the programme still has to fit the time you gave it. Adding .arms.chest.shoulders does not create three extra full programmes.',
  `Look back at your ${b.name} recommendation. Check your available days, session length and equipment. Change anything that was an optimistic guess. It is better to plan a repeatable week than to collect a perfect-looking plan you cannot use.`
 ]:[
  'Decide when your first session belongs in your calendar. Choose the place, the equipment and the small practical jobs that make starting easier. A plan for Tuesday is more useful than a promise about Monday.',
  'Give your food the same practical treatment. Save a few recipes, plan the meals you need and check the shopping list against your cupboard. Planned food is not food eaten: log what actually happened so the remaining totals stay honest.',
  'At the end of the week, review what you did and what got in the way. Keep what worked. Adjust the parts that did not. Your record is information for the next week, not a verdict on you.'
 ],
 action:i===2?'Open my meal planner':'Review my programme recommendation',href:i===2?'/meal-planner/':'/get-started/',task:i===0?'Write one practical outcome for your first month.':i===1?'Check that your chosen base, focus areas and available time agree.':'Choose a first session time and add two useful meals to your plan.'})));
